matrix-org/matrix-ios-kit

MatrixKit/Controllers/MXKAuthenticationViewController.m
Whitespace is not valid in a username, and sometimes my phone
autocompletes with a space at the end for some reason
=> Strip whitespace around usernames

MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m
Reload data source when the local history has been flushed on limited timeline room sync.
=> MXKRoomDataSource: Support server sync v2.

MatrixKit/Models/Room/MXKRoomDataSource.m
The added autoreleasepool block reduces this memory usage spike  (which happens when retrieving thousands of events on app resuming):
=> MXKRoomDataSource: Added an @autoreleasepool on queued events processing

MatrixKit/Controllers/MXKAttachmentsViewController.m
On iOS < 9: the navigation Bar cannot be hidden on viewWillAppear. We need to wait for viewDidAppear call.
=> Issue: Back failed on attachment view (iOS8).

MatrixKit/Controllers/MXKRecentListViewController.m, MatrixKit/Controllers/MXKRoomMemberListViewController.m, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/MXKDataSource.h, MatrixKit/Models/MXKDataSource.m, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Models/RoomList/MXKInterleavedRecentsDataSource.m, MatrixKit/Models/RoomList/MXKRecentsDataSource.m, MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m, MatrixKit/Models/RoomMemberList/MXKRoomMemberListDataSource.m, MatrixKit/Views/RoomMemberList/MXKRoomMemberTableViewCell.xib, README.rst, Samples/MatrixKitSample/MXKSampleJSQMessagesViewController.m, Samples/MatrixKitSample/MXKSampleMainTableViewController.m, Samples/MatrixKitSample/MXKSampleRoomMembersViewController.m
The aim of this refactoring is to handle the cell view definition at view controller level instead of data source level.
For that:
- we define 2 new methods in MXKDataSourceDelegate protocol: one to retrieve the cell view class adapted to render a cell data, another to retrieve the associated identifier used to dequeue  and reuse table or collection cells.
- we remove the definition of cell view identifiers in data source headers. These identifiers are now handled at view controller level.
=> Mxk data source refactoring

MatrixKit/Models/Account/MXKAccount.m
only when we logout or disable the account, otherwise we delete and (usually) recreate our pusher every time the app starts, which is a Bad Idea.
Should fix the problem where push turns itself off sometimes and then you get no push until you open the app again.
=> Don't delete the pusher when we close the session

MatrixKit/Models/Room/MXKRoomBubbleCellData.m, MatrixKit/Models/Room/MXKRoomBubbleCellDataStoring.h, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.h, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
+ MXKRoomDataSource: Add a new flag 'useCustomReceipts' to disable the default display of read receipts by MatrixKit.
=> MXKRoomBubbleTableViewCell: Add overlay container

MatrixKit/Categories/NSBundle+MatrixKit.h, MatrixKit/Categories/NSBundle+MatrixKit.m
If the key is not defined in this table, the localized string is retrieved from the default table "MatrixKit.strings".
=> Customize the table used to retrieve the localized version of a string.

MatrixKit/Categories/NSBundle+MatrixKit.m
The code for "Check first customized table" in mxk_localizedStringForKey did not work.
If a key has no value in the translation file, iOS does not return nil but the key itself.
There is no way on iOS to check value existence :(
The proposed fix is based on the assumption that a developer will not translate the single character string "_". With this implementation, the code does not spend its life in string comparison to check the translation value existence.
=> mxk_localizedStringForKey: Fixed translation defaulting to MatrixKit translation

MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.h, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarViewWithHPGrowingText.m, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarViewWithSimpleTextView.m
Add member display name in text input when user taps on avatar.
Note: We add here a new event to handle long press on the avatar view.
=> MXKRoomBubbleTableView: Handle avatar tap

MatrixKit/Controllers/MXKRoomViewController.h, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m
A back pagination is automatically triggered when user is scrolling close to the top. The retrieved history is added discretely to the top of bubbles table without change the current display.
=> MXKRoomViewController: Handle inconspicuous back pagination.

MatrixKit/Models/Room/MXKRoomDataSource.m
Remove the messages from the outgoing messages store only when we know there have been successfully sent.
=> BF: Outgoing Messages were not stored in case of errors (like 180s timeout)

MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Models/RoomList/MXKRecentCellData.m
The goal of this PR is to remove non required pagination requests when opening a room. It saves network data usage and boost the room content display.
The non required pagination requests occurred:
- the first time the datasource was used. In this case, the room data source made a pagination request instead of using messages from the store - which are often enough to fill the screen.
- when the user came back to a room. When coming back the code made an unexpected pagination request.
This PR depends on https://github.com/matrix-org/matrix-ios-sdk/pull/71.
=> Room page loading improvement

MatrixKit/Controllers/MXKTableViewController.m, MatrixKit/Controllers/MXKViewController.m
Do not show it if the stopActivityIndicator is called just after (less than 0.3s)
=> MXKViewController/MXKTableViewController: Improve activity indicator display.

MatrixKit/Models/Room/MXKRoomDataSource.m
Resurrect code in limitMemoryUsage to avoid to loose echoes and to mix them and sending failures
=> MXKRoomDataSource: BF: messages being sent (echoes) were sometimes displayed in red

MatrixKit/Controllers/MXKRoomViewController.m
https://github.com/vector-im/vector-ios/issues/79: If messages arrive whilst you are scrolled back, the scroll offset jumps
=> Unsuspicious back pagination bug fix

MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.h, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
Please can we have default ios long-tap to select and clipboard behaviour again?
=> Bug Fix: vector-ios #87

MatrixKit/Models/Account/MXKAccount.h, MatrixKit/Models/Account/MXKAccount.m
Related PR in vector-ios: https://github.com/vector-im/vector-ios/pull/173
Related PR in matrix-ios-console: https://github.com/matrix-org/matrix-ios-console/pull/8
=> MXKAccount: the push gateway URL must be configurable

MatrixKit/Controllers/MXKContactListViewController.m, MatrixKit/Models/MXKDataSource.h, MatrixKit/Models/MXKDataSource.m, MatrixKit/Views/MXKCellRendering.h, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.h, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
The first usage is the click on a link in the chat history to intercept universal links.
=> Added a general mechanism to let cells ask confirmation to the app before doing something

MatrixKit/Controllers/MXKRoomViewController.m
This also fixes the jump on an incoming messages when the user scrolls (even with no back pagination)
=> Fixed https://github.com/vector-im/vector-ios/issues/192: Chat screen lag during the history scrolling

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/Controllers/MXKRoomViewController.m
https://github.com/vector-im/vector-ios/issues/283
=> BugFix: Handle the error on joining a room where everyone has left

MatrixKit/Controllers/MXKAttachmentsViewController.m, MatrixKit/Controllers/MXKRoomViewController.m
This issue is related to https://github.com/vector-im/vector-ios/issues/313. It prevents the kit from trying to display an unsent media.
=> MXKRoomViewController: Do nothing when clicking on an unsent media.

MatrixKit/Models/Contact/MXKContact.h, MatrixKit/Models/Contact/MXKContact.m
Tell whether a component of the contact's displayName, or one of his matrix id/email has the provided prefix.
=> MXKContact: Add hasPrefix method

MatrixKit/Models/Room/MXKRoomBubbleCellData.m, MatrixKit/Models/Room/MXKRoomBubbleComponent.h, MatrixKit/Models/Room/MXKRoomBubbleComponent.m, MatrixKit/Models/RoomList/MXKRecentCellData.m, MatrixKit/Utils/MXKEventFormatter.h, MatrixKit/Utils/MXKEventFormatter.m
#124
This PR concerns only display of formatted html body. This allows to display markdown typed from another Matrix client.
MD typing support on iOS will be another PR.
=> Formatted body display support

MatrixKit.podspec, MatrixKit/Utils/MXKEventFormatter.h, MatrixKit/Utils/MXKEventFormatter.m
Because the NSAttributedString default HTML renderer uses WebKit on the UI thread. As we need to run in a background task, it created race conditions and the app hang forever.
#124
=> Use DTCoreText to render HTML

MatrixKit/Utils/MXKEventFormatter.h, MatrixKit/Utils/MXKEventFormatter.m
#129
And fixed newlines that were unexpectedly added between bubbles.
=> MXEventFormatter: Use the same HTML tags whitelist as matrix-react-sdk

MatrixKit/Models/RoomList/MXKRecentCellData.m, MatrixKit/Utils/MXKEventFormatter.m
https://github.com/vector-im/vector-ios/issues/494
- Ignore members profile changes during last message handling.
=> Bug Fix - Profile changes shouldn't reorder the room list

MatrixKit/Controllers/MXKCallViewController.h, MatrixKit/Controllers/MXKCallViewController.m
https://github.com/vector-im/vector-ios/issues/521
Set up or teardown the promixity monitoring and enable/disable the idle timer according to call type, state & audio route.
TODO: handle the case where an headset is used.
=> Bug Fix - Screen still tries to turn off when on a VC

MatrixKit/Models/Account/MXKAccount.m
https://github.com/vector-im/vector-ios/issues/506
According to the logs (attached to the emailed report), the applicationDidEnterBackground was ignored during the session state handling. The session was running whereas the app was backgrounded.
=> Should fix - Sync has got stuck while the app was backgrounded

MatrixKit/Controllers/MXKAttachmentsViewController.m
https://github.com/vector-im/vector-ios/issues/387
Do not force the refresh of the current attachment index on attachments update. The current index value is correct.
=> Bug Fix - Chat screen: wrong attachment is opened

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/Utils/MXKEventFormatter.m
It fixes "kick reason should displayed like the webclient" (https://github.com/vector-im/vector-ios/issues/549)
=> MXKEventFormatter: Change how the kick reason is displayed

MatrixKit/Models/Room/MXKRoomDataSource.m
Observed when all the room events are ignored because of their types.
=> Bug Fix - MXKRoomDataSource: infinite loop on empty bubbles array.

MatrixKit/Controllers/MXKRecentListViewController.h, MatrixKit/Controllers/MXKRecentListViewController.m
https://github.com/vector-im/vector-ios/issues/715
MXKRecentListViewController: observe kMXSessionDirectRoomsDidChangeNotification notification
(reload the recents table view by default).
=> Converting existing rooms to/from DMs

MatrixKit/Controllers/MXKRoomMemberDetailsViewController.m, MatrixKit/Views/MXKRoomCreationView.m
vector-im/vector-ios#715
Ensure 1:1 rooms are created with equal ops on both sides (the trusted_private_chat preset)
=> Feature - Converting existing rooms to/from DMs

MatrixKit/Models/Room/MXKRoomDataSource.m
Use the classes in https://github.com/matrix-org/matrix-ios-sdk/pull/164 to encrypt attachments. Also generate client-side thumbnails for encrypted attachments.
=> Support for encrypting attachments

MatrixKit/Controllers/MXKAttachmentsViewController.m, MatrixKit/Models/Room/MXKAttachment.h, MatrixKit/Models/Room/MXKAttachment.m, MatrixKit/Models/Room/MXKRoomDataSource.m
* Load full res image in attachments view controller for images
* Make animated gifs display in attachments view controller
* Move thumbnails to `info` which is where they're supposed to be
* Use the full res image if there is no thumbnail
=> More encrypted attachments progress:

MatrixKit/Views/MXKImageView.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
https://github.com/vector-im/vector-ios/issues/795
Prevent the cell from displaying again the image in case of reuse.
=> Bug Fix - Wrong thumbnail shown whilst uploading e2e image

MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Models/Room/MXEncryptedAttachments.h, MatrixKit/Models/Room/MXEncryptedAttachments.m, MatrixKitTests/EncryptedAttachmentsTest.m
* v1 uses 64 bits of the IV rather than all 128. It turns out
commoncrypto does this anyway and has no option to change it,
so iOS has always done this, so this is basically adding the
v: "v1" to the attachment info.
* Add unit test testing the IV wraparound behaviour (this is what
tests how many bits of the IV we're using)
* Fix base64 padder
* Check type of things we get out of the attachment dict to avoid
crashes due to unknown selectors.
=> Switch to e2e attachments spec v1

MatrixKit/Controllers/MXKCallViewController.h
The developer should use the `isBeingPresented` method and the `presentingViewController` property defined in the `UIViewController` class.
https://github.com/vector-im/vector-ios/issues/764
=> MXKCallViewController: remove `isPresented` property

MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m
[sendMessageOfType:content:success:failure:] is replaced with [sendMessageWithContent:success:failure:] where the message type is defined in the content dictionary.
=> API break - MXKRoomDataSource: `sendMessageOfType` is deprecated.

MatrixKit/Utils/Media/MXKMediaLoader.h, MatrixKit/Utils/Media/MXKMediaLoader.m, MatrixKit/Views/MXKImageView.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
- Modify the dictionary of the progress statistics in order to be able to move media loader at SDK level.
=> Move Media Loader in Matrix SDK

MatrixKit/Models/Contact/MXKContactManager.h, MatrixKit/Models/Contact/MXKContactManager.m
- deprecate localEmailContacts:
- add localContactsWithMethods: to list the local contacts who have methods which can be used to invite them or to discover matrix users.
=> MXKContactManager: List the local contacts with methods.

MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Models/RoomList/MXKRecentCellData.m
https://github.com/vector-im/riot-ios/issues/889
The issue is explained here:
https://github.com/vector-im/riot-ios/issues/889#issuecomment-272168555
=> Bug fix - Cloned rooms in rooms list

MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m
vector-im/riot-ios#894
Move the local echo suppression from `MXKRoomDataSource` to `MXEventTimeline` class.
=> Bug Fix: Riot looks to me like I'm sending the same message twice.

MatrixKit/Models/Room/MXKRoomDataSource.m
https://github.com/vector-im/riot-ios/issues/970
=> Bug Fix - Duplicated msg when going into room details

MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/Views/EncryptionKeys/MXKEncryptionKeysExportView.h, MatrixKit/Views/EncryptionKeys/MXKEncryptionKeysExportView.m
Add MXKEncryptionKeysExportView dialog.
The export action is done at the app level.
Note that the export message is huge to be correctly displayed on a 5s form factor. It can be easily improved later.
=> Keys export

MatrixKit/Models/Contact/MXKContact.h, MatrixKit/Models/Contact/MXKContact.m, MatrixKit/Models/Contact/MXKContactField.h, MatrixKit/Models/Contact/MXKContactField.m, MatrixKit/Models/Contact/MXKContactManager.h, MatrixKit/Models/Contact/MXKContactManager.m
https://github.com/vector-im/riot-ios/issues/1001
+ Bug Fix - Contact Picker: the matrix user's avatar is not updated in case of change.
=> Bug Fix - Show riot enabled local contacts in known contacts too.

MatrixKit/Views/EncryptionInfoView/MXKEncryptionInfoView.h, MatrixKit/Views/EncryptionInfoView/MXKEncryptionInfoView.m
- Updated code to follow changes due to https://github.com/matrix-org/matrix-ios-sdk/pull/244.
- Added MXKEncryptionInfoViewDelegate to be notified when the device has been verified
=> Warn unknown devices

MatrixKit.podspec, MatrixKit/Utils/MXKEventFormatter.m, MatrixKitTests/MXKEventFormatterTests.m, Podfile, Podfile.lock
This replaces with the GHMarkdownParser library with the cmark (CommonMark) library.
This also resolves #188.
signed-off-by: Avery Pierce <aapierce0@gmail.com>
=> Replace GHMarkdownParser with CommonMark

MatrixKit/Models/Room/MXKAttachment.m
https://github.com/vector-im/riot-ios/issues/1121
The thumbnail url was computed before retrieving the content url. The resulting url was nil.
=> Bug Fix - Chat screen: image thumbnails management is broken

MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Animators/MXKAttachmentAnimator.h, MatrixKit/Animators/MXKAttachmentAnimator.m, MatrixKit/Animators/MXKAttachmentInteractionController.h, MatrixKit/Animators/MXKAttachmentInteractionController.m, MatrixKit/Controllers/MXKAttachmentsViewController.h, MatrixKit/Controllers/MXKAttachmentsViewController.m, MatrixKit/Controllers/MXKRoomViewController.h, MatrixKit/Controllers/MXKRoomViewController.m
I have added animation and interaction controllers, which are reusable. Also added an option to make MXKAttachmentsViewController animatable. This pull request is the first step of https://github.com/vector-im/riot-ios/issues/1064 this issue. Afterwards, the reusable UI Elements created here will be used in Riot iOS to finish the improvement mentioned above. Please review my code.
=> Attachment viewcontroller interactive animations

MatrixKit/Controllers/MXKRoomViewController.h, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.h, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
- MXKRoomViewController: Remove the historic counters reset when a room data source is set. The counters are updated automatically when the table view is rendered (by acknowledging the last displayed event). Add the `updateRoomReadMarker` property to tell whether the read marker should follow the event acknowledgement.
- MXKRoomDataSource: add `showReadMarker` property to handle read marker display.
- MXKRoomBubbleTableViewCell: add a `readMarkerView` property to track the potential marker added into a room bubble.
Note: Nothing is done FTM at the matrix-ios-kit level to render the read marker.
vector-im/riot-meta#8
=> Read markers should be synchronised across clients

MatrixKit/Utils/MXKEventFormatter.m
https://github.com/matrix-org/matrix-ios-sdk/issues/292
=> Bug Fix: [MXSession resetRoomsSummariesLastMessage] freezes the app

MatrixKit/Models/Contact/MXKPhoneNumber.h, MatrixKit/Models/Contact/MXKPhoneNumber.m, MatrixKit/Models/Room/MXKRoomCreationInputs.h, MatrixKit/Models/Room/MXKRoomCreationInputs.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.h, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarViewWithHPGrowingText.h, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarViewWithHPGrowingText.m, MatrixKit/Views/RoomMemberList/MXKRoomMemberTableViewCell.h, MatrixKit/Views/RoomMemberList/MXKRoomMemberTableViewCell.m
Oserwise, you can't use MatrixKit files in swift files
=> Clean headers to be able to build MatrixKit pod as a module

MatrixKit/Models/Contact/MXKPhoneNumber.m, MatrixKit/Models/Room/MXKRoomCreationInputs.h, MatrixKit/Models/Room/MXKRoomCreationInputs.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.h, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarViewWithHPGrowingText.h, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarViewWithHPGrowingText.m, MatrixKit/Views/RoomMemberList/MXKRoomMemberTableViewCell.h, MatrixKit/Views/RoomMemberList/MXKRoomMemberTableViewCell.m
There is an issue with PR #282. The problem is `MXKRoomInputToolbarViewWithHPGrowingText`.  Code from this PR is incorrect since we can't use forward declaration while putting protocol conformance into the header. This is why Riot builds with fails on develop branch.
I tried to put protocol conformance into implementation file but then i figured out that in Riot in the `RoomInputToolbarView` class `HPGrowingTextViewDelegate` methods are overloaded and one of them calls parent implementation, so we can't hide protocol conformance. So i decided to revert changes in this file.
As for other files, i make the most of forward declaration in these files.
I test all my changes on Riot app and everything works fine.
=> Improvements for PR #282

MatrixKit/Views/MXKAlert.m
I found an interesting case while i was debugging issue with CallViewController. Sometimes instead of calling `dissmis:` method of `MKAlert` to hide alert, an internal variable of view controller is set to nil. And this situation introduced retain cycle. `dismiss` method release it's internal `alert` property while its called and we don't meet any retain cycle. But if the user dismiss alert just by setting variable to nil, we say hello to retain cycle. Instead of finding all of places like in the example below, it's easier to pass `weakSelf` into handler and the problem is gone.
```Objective-C
callActionSheet = [[MXKAlert alloc] initWithTitle:nil message:nil style:MXKAlertStyleActionSheet];
__weak typeof(self) weakSelf = self;
[callActionSheet …
```
=> Prevent MXKAlert from being retained in action handler

MatrixKit/Controllers/MXKRoomViewController.h, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.h, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
When the room view controller displays is based on a timeline with an initial event.
The bubble table view content is scrolled by default to display the top of this event at the center of the screen the first time it appears.
We introduce here a new property `centerBubblesTableViewContentOnTheInitialEventBottom` to let the table view center its content on the bottom part of the event. This will be useful to jump to the last unread message and display the marker view.
=> Read marker - MXKRoomViewController: Improve bubbles table view display.

MatrixKit.xcodeproj/project.pbxproj, MatrixKit/MatrixKit.h, MatrixKit/Models/Account/MXKAccount.m, MatrixKit/Models/MXKAppSettings.h, MatrixKit/Models/MXKAppSettings.m, MatrixKit/Models/Room/MXKRoomBubbleCellData.m, MatrixKit/Models/Room/MXKRoomBubbleCellDataStoring.h, MatrixKit/Models/Room/MXKRoomBubbleCellDataWithAppendingMode.m, MatrixKit/Models/Room/MXKRoomBubbleComponent.m, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Utils/MXKEventFormatter.h, MatrixKit/Utils/MXKEventFormatter.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m, MatrixKit/Views/RoomBubbleList/MXKRoomEmptyBubbleTableViewCell.h, MatrixKit/Views/RoomBubbleList/MXKRoomEmptyBubbleTableViewCell.m, MatrixKit/Views/RoomBubbleList/MXKRoomEmptyBubbleTableViewCell.xib
Read markers should be synchronised across clients
The read marker may be defined on an event which is not displayed in the room history.
We update here the MatrixKit in order to handle this kind of event in the MXKRoomBubbleCellData object.
Previously these events were ignored during the bubbles rendering. Now a bubble component is created even if the event has no actual display.
This component is useful to display the read marker in the room history, and to allow the user to jump on this read marker.
vector-im/riot-meta#8
=> Read marker

MatrixKit/Animators/MXKAttachmentAnimator.h, MatrixKit/Animators/MXKAttachmentAnimator.m, MatrixKit/Animators/MXKAttachmentInteractionController.h, MatrixKit/Animators/MXKAttachmentInteractionController.m, MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/Controllers/MXKAttachmentsViewController.m, MatrixKit/Controllers/MXKCallViewController.m, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Views/MXKTableViewCell/MXKTableViewCellWithButton.m, MatrixKit/Views/MXKTableViewCell/MXKTableViewCellWithLabelAndSwitch.xib
- Add a default value for `callStatusLabel`
- Fix problems(see console in Riot when you're a scrolling on the settings screen) with constraints in `MXKTableViewCellWithLabelAndSwitch`. Remove label's center constraint and change its bottom's value to 3.
- Add `prepareForReuse` to `MXKTableViewCellWithButton`. Scroll to the bottom on the settings screen in Riot and then scroll to top and you can see how text is flashing on sign out button. I fixed this
- Add missed `nonatomic` attribute for properties
=> Small improvements

MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Controllers/MXKCallViewController.m, MatrixKit/Utils/MXKSoundPlayer.h, MatrixKit/Utils/MXKSoundPlayer.m
I tried to make `MXKSoundPlayer` as simple as it could be. It suites for tasks of `MXKCallViewController` and can be improved in the future. There are problems with background music and `MXCallViewController` since `MXKCallViewController` doesn't handle all cases. With my PR there is no such problem. It also fixes [1283](https://github.com/vector-im/riot-ios/issues/1283) and the problem with sound after `MXKCallViewController` is dismissed (this problem is reproduced in the last buid from TestFlight. I mentioned about it to you earlier).
**NOTE:** It works great without CallKit but if you try to add CallKit you will notice that after the call is connected, the sound is gone. I have trying to figure out what the problem is. It's obviously that it's something connected with AVAudioSession …
=> MXKSoundPlayer

MatrixKit/Controllers/MXKCallViewController.m
=> Make creation methods of MXKCallViewController to be generic

MatrixKit/Controllers/MXKCallViewController.m, MatrixKit/Utils/MXKSoundPlayer.h, MatrixKit/Utils/MXKSoundPlayer.m
I decided to move out `AVAudioSession` deactivation from `stopPlaying` method since we need more granular control on when we need to deactivate `AVAudioSession`. Now AVAudioSession is deactivated when it's 100% no sound to play.
As i told earlier we need to start playing ringback sound for outgoing calls only when the system has succesfully activates `AVAudioSession` otherwise the ringback sound will be gone. So i [decided](https://github.com/matrix-org/matrix-ios-sdk/pull/317) to post a global notification about this event and handle it by setting `isRinging` property to `YES` when all criterias are met.
With both PRs we won't have any issues with the sound. I have tested this code and it works well.
Maybe you have your own mind on how we can handle these situations. I'm glad to hear …
=> Fix issues with sound

MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m, MatrixKit/Views/RoomBubbleList/MXKRoomOutgoingBubbleTableViewCell.m
This regression was introduced when we decided to keep a component for each event, even for those without display.
We fix tap on bubble handling too.
https://github.com/vector-im/riot-ios/issues/1361
=> Bug Fix - Chat screen: the sender avatar is missing.

MatrixKit/Controllers/MXKTableViewController.m, MatrixKit/Controllers/MXKViewController.m
https://github.com/vector-im/riot-meta/issues/22
=> Prepare Dark Theme

MatrixKit/Categories/NSBundle+MXKLanguage.h, MatrixKit/Categories/NSBundle+MXKLanguage.m, MatrixKit/Categories/NSBundle+MatrixKit.m
Apply the same hack in NSBundle+MXKLanguage to manage fallback
=> Translation: Make language fallback work for MatrixKit strings

MatrixKit/Controllers/MXKCallViewController.m
Due to the last changes `MXCallViewController` wasn't dismissed in most cases. See [issue](https://github.com/vector-im/riot-ios/issues/1405). This PR fix this. Also i changed order of capturing `weakSelf` in alert action's handler since it's safer to capture `weakSelf` firstly and then check strong reference for nil.
=> Fix problems with MXCallViewController dismissing

MatrixKit/Controllers/MXKCallViewController.m
See [#933](https://github.com/vector-im/riot-ios/issues/933), [#359](https://github.com/matrix-org/matrix-ios-sdk/pull/359)
This check doesn't do anything since `event` is always nil for `MXCallStateConnected` state
```
case MXCallStateConnected:
if (event)
{
...
}
```
=> Fix issue #933

MatrixKit/Utils/MXKEventFormatter.m
Fixes vector-im/riot-ios#1500.
It turns out that stripping the leading and ending `<p>`
tags was done in a simplistic way, which ignored the fact
that the string may contain multiple paragraphs.
For example, stripping the leading and ending `<p>` from:
<p>line 1</p>
<p>line 2</p>
(incorrectly) used to produce:
line 1</p>
<p>line 2
With this patch, we only do leading/ending `<p>` stripping
if the HTML string contains exactly 1 paragraph.
Signed-off-by: Slavi Pantaleev <s.pantaleev@gmail.com>
=> Fix garbled HTML paragraph syntax during markdown conversion

MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m
vector-im/riot-ios#1521
Force compression for HEIC images so that the kit creates JPEG images for them.
=> BF: Riot on iOS11 sends images as HEIC format, which nothing else can display

MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Categories/UIScrollView+MatrixKit.h, MatrixKit/Categories/UIScrollView+MatrixKit.m, MatrixKit/Controllers/MXKContactListViewController.m, MatrixKit/Controllers/MXKRecentListViewController.m, MatrixKit/Controllers/MXKRoomMemberListViewController.m, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Controllers/MXKSearchViewController.m, MatrixKit/Controllers/MXKTableViewController.m, MatrixKit/MatrixKit.h
- MXKRoomViewController: fix header layout
- Add UIScrollView+MatrixKit category to handle the adjusted content inset which is not defined before iOS 11.
=> Fix iOS11 disruption

MatrixKit/Utils/MXKEventFormatter.m
We remove now the bottom spacing only for the last paragraph.
https://github.com/vector-im/riot-ios/issues/1500
=> Bug Fix -Wrong paragraph rendering in the room messages.

MatrixKit/Models/Account/MXKAccountManager.h, MatrixKit/Models/Account/MXKAccountManager.m
One of the useful things that comes with this improvement is that we will be able to write  `[MXKAccountManager sharedManager].accounts.firstObject.mxRestClient` instead of `[[MXKAccountManager sharedManager].accounts.firstObject mxRestClient]`
=> Add generic annotations for MXKAccountManager

MatrixKit/Controllers/MXKAccountDetailsViewController.m, MatrixKit/Controllers/MXKNotificationSettingsViewController.m, MatrixKit/Controllers/MXKRoomMemberDetailsViewController.m, MatrixKit/Controllers/MXKRoomSettingsViewController.m, MatrixKit/Models/PublicRoomList/DirectoryServerList/MXKDirectoryServersDataSource.m, MatrixKit/Models/RoomList/MXKRecentsDataSource.m, MatrixKit/Models/RoomMemberList/MXKRoomMemberListDataSource.m, MatrixKit/Models/Search/MXKSearchDataSource.m
return a fake cell to prevent app from crashing.
=> tableView cellForRowAtIndexPath:

MatrixKit/Controllers/MXKRoomViewController.h, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.h, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m
and must be downloaded from iCloud.
https://github.com/vector-im/riot-ios/issues/1654
- API breaks: We consider the full-sized image data instead of the local image URL (this is required to handle correctly image stored in iCloud).
MXKRoomInputToolbarView :
`(void)roomInputToolbarView:(MXKRoomInputToolbarView*)toolbarView sendImage:(NSURL*)imageLocalURL withMimeType:(NSString*)mimetype;`
is replaced with
`(void)roomInputToolbarView:(MXKRoomInputToolbarView*)toolbarView sendImage:(NSData*)imageData withMimeType:(NSString*)mimetype;`
`(void)sendSelectedImage:(UIImage*)selectedImage withCompressionMode:(MXKRoomInputToolbarCompressionMode)compressionMode andLocalURL:(NSURL*)imageURL`
is replaced with
`(void)sendSelectedImage:(NSData*)imageData withMimeType:(NSString *)mimetype …
=> Bug Fix - Failed to send photos which are not stored on the local device

MatrixKit/Controllers/MXKGroupListViewController.m, MatrixKit/Models/Group/MXKGroupCellData.m, MatrixKit/Models/Group/MXKSessionGroupsDataSource.h, MatrixKit/Models/Group/MXKSessionGroupsDataSource.m, MatrixKit/Views/Group/MXKGroupTableViewCell.m
- MXKSessionGroupDataSource: support the group summary refresh
vector-im/riot-meta#114
=> Groups: self-management of membership of groups

MatrixKit/Models/Account/MXKAccountManager.m, MatrixKit/Models/MXKAppSettings.h, MatrixKit/Models/MXKAppSettings.m
into a file instead of NSUserDefaults.
This data should be then more accessible for background processing like handling push notifications.
https://github.com/vector-im/riot-ios/issues/1696
=> Missing Push Notifications: Store MXKAccount data (like user credentials) 

MatrixKit/Controllers/MXKRoomViewController.m
(https://github.com/vector-im/riot-ios/issues/1754)
=> BF: iPhone X: room messages overlap the room activity view

MatrixKit/Models/Room/MXKRoomBubbleCellData.m, MatrixKit/Models/Room/MXKRoomBubbleCellDataStoring.h, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Utils/MXKTools.h, MatrixKit/Utils/MXKTools.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
MXKRoomDataSource: Force a refresh on flair settings change.
MXKRoomBubbleCellData: keep update the flair of the sender.
MXKRoomBubbleTableViewCell: Display the sender flair if any
TODO: display the full flair list when the user clicks on the displayed flair.
vector-im/riot-meta#118
=> Groups: Display flair for users in room history.

MatrixKit/Models/Room/MXKRoomBubbleCellData.m, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m
by managing the related groups of a room at the RoomDataSource level instead of at the bubble level
vector-im/riot-meta#118
=> Enhance the flair handling,

MatrixKit/Utils/MXKEventFormatter.m
=> MXKEventFormatter: Emotes which contain a single emoji are expanded to be enormous 

MatrixKit/Models/Account/MXKAccount.m
https://github.com/vector-im/riot-ios/issues/1780
This bug revealed a more generic one where room summaries did not use any event filter. This made their display not aligned with messages displayed in room history.
=> Community: Room summary should not display notices about groups

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/Assets/MatrixKitAssets.bundle/fr.lproj/MatrixKit.strings, MatrixKit/Controllers/MXKAttachmentsViewController.m, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/MXKAppSettings.m, MatrixKit/Models/Room/MXKAttachment.h, MatrixKit/Models/Room/MXKAttachment.m, MatrixKit/Models/Room/MXKRoomBubbleCellData.m, MatrixKit/Models/Room/MXKRoomBubbleCellDataStoring.h, MatrixKit/Models/Room/MXKRoomBubbleCellDataWithAppendingMode.m, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Utils/MXKEventFormatter.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.h, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m, MatrixKit/Views/RoomBubbleList/MXKRoomIOSOutgoingBubbleTableViewCell.m
=> Render sticker events in the timeline

MatrixKit/Controllers/MXKAccountDetailsViewController.m, MatrixKit/Controllers/MXKNotificationSettingsViewController.m, MatrixKit/Controllers/MXKRoomMemberDetailsViewController.m, MatrixKit/Controllers/MXKRoomMemberListViewController.m, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/Account/MXKAccount.m, MatrixKit/Models/Group/MXKSessionGroupsDataSource.m, MatrixKit/Models/RoomList/MXKRecentsDataSource.m, MatrixKit/Utils/MXKConstants.h, MatrixKit/Utils/MXKConstants.m, MatrixKit/Views/DeviceView/MXKDeviceView.m, MatrixKit/Views/EncryptionInfoView/MXKEncryptionInfoView.m, MatrixKit/Views/MXKEventDetailsView.m, MatrixKit/Views/MXKRoomCreationView.m, MatrixKit/Views/RoomTitle/MXKRoomTitleView.m, MatrixKit/Views/RoomTitle/MXKRoomTitleViewWithTopic.m
Add the account identifier in userInfo dictionary to let the listener know which account is concerned by the error.
https://github.com/vector-im/riot-ios/issues/1839
=> Improve Error Notifications

MatrixKit/Models/Room/MXKRoomBubbleCellData.h, MatrixKit/Models/Room/MXKRoomBubbleCellData.m, MatrixKit/Models/Room/MXKRoomBubbleComponent.h, MatrixKit/Models/Room/MXKRoomBubbleComponent.m, MatrixKit/Utils/MXKEventFormatter.h, MatrixKit/Utils/MXKEventFormatter.m, MatrixKit/Utils/MXKTools.h, MatrixKit/Utils/MXKTools.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
vector-im/riot-ios#1857
This is a bit fragile but I have not found a better workaround.
=>  HTML Rendering: Fix the display of side borders of HTML blockquotes

MatrixKit/Utils/MXKEventFormatter.m, MatrixKit/Utils/MXKTools.h, MatrixKit/Utils/MXKTools.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
Close vector-im/riot-ios#1877
Make sure we do not change anymore the NSAttributeString background color and manage the 2 ways how DTCoreText manages HTML blockquotes.
Live examples could be fine at https://riot.im/develop/#/room/#test_quotes:matrix.org.
=> Fix: Quotes (by themselves) render as white blocks

MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Views/BarButtonItem/MXKBarButtonItem.h, MatrixKit/Views/BarButtonItem/MXKBarButtonItem.m
Add a MXKBarButtonItem, UIBarButtonItem subclass with convenient action block. Avoid to use selector.
=> Add UIBarButtonItem subclass with convenient action block

CHANGES.rst, MatrixKit/Models/Room/MXKRoomBubbleCellData.h, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
https://github.com/vector-im/riot-ios/issues/1899
=> MXKRoomBubbleCellData: add a `readReceipts` member to cache read receipts data

MatrixKit/Controllers/MXKCallViewController.m, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/Search/MXKSearchCellData.m, MatrixKit/Views/PushRule/MXKPushRuleCreationTableViewCell.m, MatrixKit/Views/PushRule/MXKPushRuleTableViewCell.m
We have MXRoomSummary.displayName now
Follows https://github.com/matrix-org/matrix-ios-sdk/pull/529.
=> MXRoomState: Remove displayName property

CHANGES.rst, MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/Controllers/MXKRoomViewController.h, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Models/Room/MXKSendReplyEventStringLocalizations.h, MatrixKit/Models/Room/MXKSendReplyEventStringLocalizations.m, MatrixKit/Models/Room/MXKSlashCommands.h, MatrixKit/Models/Room/MXKSlashCommands.m
Implement reply to an event with text message in MXKRoomDataSource.
https://github.com/vector-im/riot-ios/issues/1911
=> Replies: Implement sending

MatrixKit/Controllers/MXKCallViewController.m, MatrixKit/Models/Account/MXKAccount.m, MatrixKit/Models/Contact/MXKContactManager.m, MatrixKit/Models/MXKAppSettings.h, MatrixKit/Models/MXKAppSettings.m, MatrixKit/Utils/MXKEventFormatter.m, MatrixKit/Views/RoomTitle/MXKRoomTitleViewWithTopic.m
Part of https://github.com/vector-im/riot-ios/issues/1931
Fix some async bits and add MXKAppSettings.syncWithLazyLoadOfRoomMembers to use LL server side.
=> Lazy loading server side

MatrixKit/Models/Search/MXKSearchDataSource.m
Use profile info sent in the search response.
Part of https://github.com/vector-im/riot-ios/issues/1931
=> Lazy-loading: Fix search display

CHANGES.rst, MatrixKit/Models/Room/MXKRoomDataSource.m
[MXKRoomDataSource] Fix a multithreading issue that caused a crash when `bubbles` property was mutated while being enumerated.
Fix issue https://github.com/vector-im/riot-ios/issues/1953
=> [MXKRoomDataSource] Fix a multithreading issue that caused a crash

MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarViewWithHPGrowingText.m, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarViewWithSimpleTextView.m
As mention in issue https://github.com/vector-im/riot-ios/issues/1959 keyboard is switching to alphabet after sending a message with any keyboard type. 
This was introduce in order to have same behavior as Apple Messages application, switch back to alphabet keyboard when sending a message with numbers and punctuation keyboard.
As there is currently no future proof way or clear public API to detect Apple Emoji keyboard and custom keyboard we remove this behavior for the moment.
=> Remove keyboard type reset in MXKRoomInputToolbar... classes

CHANGES.rst, MatrixKit/Controllers/MXKCallViewController.m, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Views/RoomTitle/MXKRoomTitleView.m, MatrixKit/Views/RoomTitle/MXKRoomTitleViewWithTopic.m
vector-im/riot-ios/issues/2031
Make sure event listeners are released. Also fixed other occurrences of the issue
=>  MXKCallViewController: Fix crash in [MXKCallViewController callRoomStateDidChange:]

CHANGES.rst, MatrixKit/Controllers/MXKCallViewController.m, MatrixKit/Models/Contact/MXKContactManager.m, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Views/RoomTitle/MXKRoomTitleView.m, MatrixKit/Views/RoomTitle/MXKRoomTitleViewWithTopic.m
vector-im/riot-ios/issues/2032
by adding a sanity check.
=> Fix crash in [MXKContactManager refreshLocalContacts] 

CHANGES.rst, MatrixKit/Models/MXKAppSettings.m, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m
to display a full page without additional homeserver request. This sync limit depends on the device the app is running
https://github.com/vector-im/riot-ios/issues/1931
=>  Sync Filter: Get enough messages from /sync requests

CHANGES.rst, MatrixKit/Controllers/MXKRoomViewController.m
https://github.com/vector-im/riot-ios/issues/2040
Fix it by increasing the threshold value that determines that the scroll view is at the its bottom
=> BF: No automatic scroll down when posting a new message

CHANGES.rst, MatrixKit/Models/Room/MXKRoomDataSource.m
vector-im/riot-ios/issues/2041
=> MXKRoomDataSource: Fix crash when opening a room with unsent message

CHANGES.rst, MatrixKit/Models/Account/MXKAccount.m
10 was definitely not enough on Giom's iPhone.
=> Sync Filter: Refine limit value. Use 15 messages for iPhone 6 & similar screen size

CHANGES.rst, MatrixKit/Models/Room/MXKRoomDataSource.m
Fixes vector-im/riot-ios/issues/2058
=> BF: MXKRoomDataSource: roomState was not updated

CHANGES.rst, MatrixKit/Controllers/MXKCallViewController.m
Fixes https://github.com/vector-im/riot-ios/issues/2079
Regression made with LL in commit b6010fa2.
=> MXKCallViewController: Fix crash in callRoomStateDidChange

CHANGES.rst, MatrixKit/Controllers/MXKAccountDetailsViewController.m, MatrixKit/Controllers/MXKAttachmentsViewController.m, MatrixKit/Controllers/MXKCallViewController.m, MatrixKit/Controllers/MXKRoomMemberDetailsViewController.m, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/Contact/MXKContactField.h, MatrixKit/Models/Contact/MXKContactField.m, MatrixKit/Models/PublicRoomList/DirectoryServerList/MXKDirectoryServerCellData.m, MatrixKit/Models/PublicRoomList/DirectoryServerList/MXKDirectoryServerCellDataStoring.h, MatrixKit/Models/PublicRoomList/DirectoryServerList/MXKDirectoryServersDataSource.m, MatrixKit/Models/Room/MXKAttachment.h, MatrixKit/Models/Room/MXKAttachment.m, MatrixKit/Models/Room/MXKRoomBubbleCellData.m, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Utils/EventFormatter/MXKEventFormatter.m, MatrixKit/Views/Account/MXKAccountTableViewCell.m, MatrixKit/Views/MXKCollectionViewCell/MXKMediaCollectionViewCell.m, MatrixKit/Views/MXKImageView.h, MatrixKit/Views/MXKImageView.m, MatrixKit/Views/MXKReceiptSendersContainer.h, MatrixKit/Views/MXKReceiptSendersContainer.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m, MatrixKit/Views/RoomBubbleList/MXKRoomOutgoingAttachmentBubbleCell.m, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m, MatrixKit/Views/RoomMemberList/MXKRoomMemberTableViewCell.m, MatrixKit/Views/Search/MXKSearchTableViewCell.m
Improvements:
* Replace the deprecated MXMediaManager and MXMediaLoader interfaces use (see matrix-org/matrix-ios-sdk/pull/593).
Deprecated API:
* MXKAttachment: the properties "actualURL" and "thumbnailURL" are deprecated because only Matrix Content URI should be considered now.
* MXKAttachment: the property "cacheThumbnailPath" is deprecated, use "thumbnailCachePath" instead.
* MXKAttachment: [initWithEvent:andMatrixSession:] is deprecated, use [initWithEvent:andMediaManager:] instead.
* MXKImageView: [setImageURL:withType:andImageOrientation:previewImage:] is deprecated, use [setImageURI:withType:andImageOrientation:previewImage:mediaManager] or [setImageURI:withType:andImageOrientation:toFitViewSize:withMethod:previewImage:mediaManager] instead.
* MXKReceiptSendersContainer: the …
=> MXMediaManager/MXMediaLoader: Do not allow non-mxc content URLs

MatrixKit/Models/Room/MXKAttachment.m
required: https://github.com/matrix-org/matrix-ios-sdk/pull/598
=> MXKAttachment: use the new MXMediaManager interfaces to download encrypted content.

CHANGES.rst, MatrixKit/Controllers/MXKWebViewViewController.h, MatrixKit/Controllers/MXKWebViewViewController.m
- Make it open links with `target="_blank"` within the webview.
- Improve back navigation by resetting initial right buttons.
Required to display html pages for https://github.com/vector-im/riot-ios/issues/1939.
=> MXKWebViewController:

MatrixKit/Controllers/MXKAuthenticationViewController.m, MatrixKit/Views/Authentication/MXKAuthInputsView.h
We cannot see anymore a reason to reset everything with `self.authType = _authType;` in `viewWillAppear`.
That breaks navigation for https://github.com/vector-im/riot-ios/issues/1939. When user went back from a policy content screen, he ended up to the email screen instead of the expected list of policies.
=> MXKAuthenticationVC: Code cleaning

CHANGES.rst, MatrixKit/Models/Contact/MXKContactManager.m
The list of the local contacts with methods is empty if they are retrieved before triggering [MXKContactManager refreshLocalContacts].
=> Bug Fix: Unexpected empty local contacts list

CHANGES.rst, MatrixKit/Models/Room/MXKAttachment.h, MatrixKit/Models/Room/MXKAttachment.m, MatrixKit/Views/MXKImageView.m
fixes vector-im/riot-ios/issues/1122
Fix a race condition where the image download completes whereas the cell has been reused for another image.
=> BF: Chat screen: wrong thumbnail observed during scrollback

CHANGES.rst, MatrixKit/Views/Authentication/MXKAuthenticationFallbackWebView.m
Fixes vector-im/riot-ios#2301.
=> Handle device_id returned from the fallback login page

CHANGES.rst, MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Views/MXKMessageTextView.h, MatrixKit/Views/MXKMessageTextView.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.h, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m, MatrixKit/Views/RoomBubbleList/MXKRoomIncomingTextMsgBubbleCell.xib, MatrixKit/Views/RoomBubbleList/MXKRoomIncomingTextMsgWithoutSenderInfoBubbleCell.xib, MatrixKit/Views/RoomBubbleList/MXKRoomOutgoingTextMsgBubbleCell.xib, MatrixKit/Views/RoomBubbleList/MXKRoomOutgoingTextMsgWithoutSenderInfoBubbleCell.xib
Handle quick tap on a link in a `MXKRoomBubbleTableViewCell`. Fix https://github.com/vector-im/riot-ios/issues/728.
Add `MXKMessageTextView` an UITextView with link detection without text selection.
=> BF Riot: Quickly tapping on a URL in a message highlights the message rather than opening the URL

MatrixKit/Models/Account/MXKAccount.m, MatrixKit/Models/Account/MXKAccountManager.m, MatrixKit/Utils/MXKTools.h, MatrixKit/Utils/MXKTools.m
vector-im/riot-ios/issues/2348
=> Push: Add logs to track spontaneously disabling

CHANGES.rst, MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m
Fix vector-im/riot-ios/issues/2148
=> BF Riot: Room Upgrades: Room appears twice in the rooms list

MatrixKit/Models/Room/MXKRoomDataSource.m
so that there is an extra "whitespaces" when the 1st reaction happens and so on
=> Reactions: Force to refresh the computation of the vertical "whitespaces"

MatrixKit/Models/Room/MXKRoomDataSource.m
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/676
Main use cases for vector-im/riot-ios#2489.
- manage local echoes for edits on sent messages
- support edits on local echoes
There is still an issue with:
- support edits on messages being sent
The edited message stays displayed in sending state. But this issue is due to a MatrixKit behavior and will be managed in a separate PR.
=> Edits: support local echo

MatrixKit/Models/Room/MXKRoomDataSource.m
Part of https://github.com/vector-im/riot-ios/issues/2489:
- support edits on messages being sent
They stayed in sending (grey) state. The reason is that the id of the event has changed during the operation from a local event id to the final event id. We need to follow this change
=> Edits: Fix edit of a message being sent

CHANGES.rst, MatrixKit/Models/MXKAppSettings.m, MatrixKit/Models/Room/MXKRoomBubbleCellData.m, MatrixKit/Models/Room/MXKRoomDataSource.m
and support RRs on non displayed events (edits and reactions)
This PR fixes https://github.com/vector-im/riot-ios/issues/2440.
Commits can be reviewed one by one.
=> Move RRs data handling to the kit

MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Categories/MXAggregatedReactions+MatrixKit.h, MatrixKit/Categories/MXAggregatedReactions+MatrixKit.m, MatrixKit/MatrixKit.h, MatrixKit/Models/Room/MXKRoomDataSource.m
Fixes https://github.com/vector-im/riot-ios/issues/2508.
Note this PR is based on the `[MXKTools isSingleEmojiString:]` method that has a [bug](https://github.com/vector-im/riot-ios/issues/2479) with latest emojis but it works for the 8 emojis we use by default
=> Reactions: Hide all reactions that aren't a single emoji

MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m
vector-im/riot-ios/issues/2553
=> Reactions: Reinstate the ability to react with non-unicode keys

CHANGES.rst, MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/Controllers/MXKAccountDetailsViewController.m, MatrixKit/Models/Account/MXKAccount.h, MatrixKit/Models/Account/MXKAccount.m, MatrixKit/Models/Account/MXKAccountManager.m
Closes vector-im/riot-ios#2348.
PR can be reviewed commit by commit.
Key changes:
- `[MXKAccount enablePushKitNotifications:::]` is now async.
- There is a new `hasPusherForPushKitNotifications` property replacing the old `enablePushKitNotifications` property. Its meaning has changed a bit. It now indicates the last successful pusher operation (enabling or disabling).
- We do not reset it anymore in case of error, which was the root of the issue.
=>  BF: Push notifications are spontaneously disabling themselves

CHANGES.rst, MatrixKit/Controllers/MXKAuthenticationViewController.h, MatrixKit/Controllers/MXKAuthenticationViewController.m, MatrixKit/Models/Account/MXKAccount.h, MatrixKit/Models/Account/MXKAccount.m, MatrixKit/Models/Account/MXKAccountManager.h, MatrixKit/Models/Account/MXKAccountManager.m, MatrixKit/Views/Authentication/MXKAuthInputsView.h
vector-im/riot-ios/issues/2540
=> Support soft logout

CHANGES.rst, MatrixKit/Controllers/MXKAuthenticationViewController.m, MatrixKit/Models/Account/MXKAccount.m, MatrixKit/Models/Contact/MXKContactManager.m, MatrixKit/Models/MXK3PID.m, MatrixKit/Views/Authentication/MXKAuthInputsView.h
vector-im/riot-ios/issues/2647
Requires matrix-org/matrix-ios-sdk/pull/706
=> Use MXIdentityService to perform identity server requests

CHANGES.rst, MatrixKit/Models/Contact/MXKContact.m, MatrixKit/Models/Contact/MXKEmail.h, MatrixKit/Models/Contact/MXKEmail.m
Ease the email addresses handling by storing them in lowercase (and ignoring the fact that the the local part is supposed to be case sensitive).
=> MXKEmail: force in lowercase the email address

CHANGES.rst, MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/Views/DeviceView/MXKDeviceView.m
Part of vector-im/riot-ios/issues/2662
=> MXKDeviceView: Make clear that device names are publicly readable

CHANGES.rst, MatrixKit/Controllers/MXKAuthenticationViewController.m, MatrixKit/Models/Account/MXKAccount.m, MatrixKit/Models/Contact/MXKContactManager.m, MatrixKit/Models/MXK3PID.m
Handle vector-im/riot-ios/issues/2603 and vector-im/riot-ios/issues/2652.
Require matrix-org/matrix-ios-sdk/pull/712
=> Support identity server v2 API

CHANGES.rst, MatrixKit/Controllers/MXKAuthenticationViewController.h, MatrixKit/Controllers/MXKAuthenticationViewController.m
Fixes vector-im/riot-ios/issues/2686
Requires: https://github.com/matrix-org/matrix-ios-sdk/pull/714
Get the IS from wellknown before checking we need to display it.
=> Privacy: Use wellknown to discover the IS of a custom HS

CHANGES.rst, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
Fix vector-im/riot-ios/issues/2738
=> MXKRoomBubbleTableViewCell: Fix issue with links too easily touchable on iOS 13

MatrixKit/Models/MXK3PID.m
This implements ([MSC2078](https://github.com/matrix-org/matrix-doc/pull/2078)).
This is a quick c+p from https://github.com/matrix-org/matrix-ios-sdk/pull/728.
We will completely remove MXK3PID when refactoring login/registration.
Part of https://github.com/vector-im/riot-ios/issues/2731.
Note: this has not been tested because msisdn add is disabled on registration on matrix.org.
=> MXK3PID: Privacy: Sending Third-Party Request Tokens via the Homeserver

MatrixKit/Controllers/MXKAuthenticationViewController.m
so that MXKAccountManager has one
Before this fix, MXKAccountManager uses the IS only after an app restart.
=> BF: Set the identity server before creating the MXKAccount too

CHANGES.rst, MatrixKit/Models/Contact/MXKContactManager.m
Do it once per new matrix session.
The full lookup (done by updateMatrixIDsForAllLocalContacts) will be triggered by refreshMatrixContacts if needed.
Add an assert on updateMatrixIDsForAllLocalContacts to avoid to call it before data was loaded (by refreshMatrixContacts).
=> MXKContactManager: Limit the number of full lookups

CHANGES.rst, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/Room/MXKAttachment.m
Passing nil to `-[UIPasteboard setString:]` causes a crash whereas `string` property is nullable (See Radar issue https://openradar.appspot.com/36063433).
=> Pasteboard: Fix a crash when passing a nil object

CHANGES.rst, MatrixKit/Utils/EventFormatter/MXKEventFormatter.h, MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
Fix vector-im/riot-ios/issues/2154
=> MXKEventFormatter: In the case of "in reply to" event, replace the user Matrix ID by his display name when available

CHANGES.rst, MatrixKit/Models/Group/MXKSessionGroupsDataSource.m
Part of vector-im/riot-ios/issues/2793
=> Groups: Load them only after the session got sync'ed with the homeserver

MatrixKit/Views/EncryptionInfoView/MXKEncryptionInfoView.m
Follow API changes made in https://github.com/matrix-org/matrix-ios-sdk/pull/762:
- [MXCrypto downloadKeys:]
- MXDeviceInfo.trustLevel
For now, we just use `MXDeviceInfo.trustLevel.localVerificationStatus` to keep it working as before. Another [task](https://github.com/vector-im/riot-ios/issues/2914) will be to replace `MXDeviceInfo.trustLevel.localVerificationStatus` by `MXDeviceInfo.trustLevel.isVerified` to handle cross-signed devices.
=> Cross-signing: Fix API breaks

CHANGES.rst, MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
Fix vector-im/riot-ios/issues/2910
=> E2E: Hide duplicate message warnings

CHANGES.rst, MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
Closes vector-im/riot-ios#2939.
=> MXKEventFormatter: E2E, hide the algo used when turning on encryption

CHANGES.rst, MatrixKit/Models/Account/MXKAccount.m
Implemented logic to use a secondary appId for debug configuration.
=> Logic to use a secondary appId for debug

MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m
to make the app breath again.
On my  account,  just after signing in,`[RecentsDataSource refreshRoomsSections]` is now called 30 times instead of more than 2000 before.
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/823.
Part of the work for vector-im/riot-ios#3105.
=> MXKSessionRecentsDataSource: Throttle room summary updates

CHANGES.rst, MatrixKit/Controllers/MXKAuthenticationViewController.m
=> Remove bottomLayoutGuide and content view equal width constraints

MatrixKit/Models/Room/MXKRoomDataSource.m
- some observers/listeners were not correctly removed. The delegate is defined as a weak property, it is not reseted anymore at the dataSource level when it is released.
These changes prevent us from creating multiple observers/listeners at each new delegate.
We have to think of a better solution if we really want to remove some observers/listener when the dataSource is unused (no delegate defined)
=> MXKRoomDataSource.m: code enhancement

MatrixKit/Models/Room/MXKRoomDataSourceManager.m
Do not call `[finalizeInitialization]` on the new loaded RoomDataSource. This is already done by RoomDataSource class before returning the instance
=> MXKRoomDataSourceManager: enhancement

CHANGES.rst, MatrixKit.podspec
Update DTCoreText library to 1.6.23 minimum to be sure to not reference UIWebView.
=> Podspec: Update DTCoreText dependency to 1.6.23 minimum

CHANGES.rst, MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
Part of vector-im/riot-ios#3282
=> Use `you` instead of display name on notice events

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.12.11.
Notes:
- This PR targets `release/0.12.11/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.12.11/master` into `master` to tag the release.
--- …
=> Release 0.12.11

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.12.12.
Notes:
- This PR targets `release/0.12.12/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.12.12/master` into `master` to tag the release.
--- …
=> Release 0.12.12

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.12.15.
Notes:
- This PR targets `release/0.12.15/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.12.15/master` into `master` to tag the release.
--- …
=> Release 0.12.15

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.12.16.
Notes:
- This PR targets `release/0.12.16/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.12.16/master` into `master` to tag the release.
--- …
=> Release 0.12.16

CHANGES.rst, MatrixKit/Controllers/MXKAuthenticationViewController.m, MatrixKit/Models/Account/MXKAccount.m, MatrixKit/Models/Account/MXKAccountManager.m, MatrixKit/Models/MXKAppSettings.m, MatrixKit/Models/Room/MXKRoomBubbleComponent.m, MatrixKit/Views/RoomTitle/MXKRoomTitleViewWithTopic.m
vector-im/riot-ios/issues/3577.
This reverts #646. Game rules have changed. We cannot use/abuse PushKit as before iOS13 SDK. We have to use APNS. So, we can safely clean PushKit pusher.
This mitigates the race condition where https://github.com/vector-im/element-ios/pull/3578 removes the pusher while `MXAccount` can refresh it in parallel on a `MXSession` state change. At the end of the refresh, the pusher is restored :/
This works because https://github.com/vector-im/element-ios/pull/3578 does not clear the `MXKAccount.hasPusherForPushKitNotifications`, which is still true after https://github.com/vector-im/element-ios/pull/3578
=> PushKit: Delete any pending PushKit pusher

CHANGES.rst, MatrixKit.podspec, MatrixKit/Assets/MatrixKitAssets.bundle/ru.lproj/MatrixKit.strings, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.12.22.
Notes:
- This PR targets `release/0.12.22/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.12.22/master` into `master` to tag the release.
--- …
=> Release 0.12.22

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.12.24.
Notes:
- This PR targets `release/0.12.24/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.12.24/master` into `master` to tag the release.
--- …
=> Release 0.12.24

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.12.26.
Notes:
- This PR targets `release/0.12.26/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.12.26/master` into `master` to tag the release.
--- …
=> Release 0.12.26

CHANGES.rst, MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Controllers/MXKPreviewViewController.h, MatrixKit/Controllers/MXKPreviewViewController.m, MatrixKit/Controllers/MXKRoomViewController.h, MatrixKit/Controllers/MXKRoomViewController.m
This property is used for showing or hiding the actions button in document preview. Part of fix for https://github.com/vector-im/element-ios/issues/3864 property
=> Added allowActionsInDocumentPreview property to MXKRoomViewController

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.13.4.
Notes:
- This PR targets `release/0.13.4/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.13.4/master` into `master` to tag the release.
--- …
=> Release 0.13.4

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.13.6.
Notes:
- This PR targets `release/0.13.6/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.13.6/master` into `master` to tag the release.
--- …
=> Release 0.13.6

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.13.7.
Notes:
- This PR targets `release/0.13.7/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.13.7/master` into `master` to tag the release.
--- …
=> Release 0.13.7

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.13.8.
Notes:
- This PR targets `release/0.13.8/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.13.8/master` into `master` to tag the release.
--- …
=> Release 0.13.8

CHANGES.rst, MatrixKit/Models/Contact/MXKContactManager.m
Fix vector-im/element-ios/issues/3984
Thanks to the magic of our auth screens, we can have such bugs :/
=> Login screen: Unexpected request to access the contact book

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.13.9.
Notes:
- This PR targets `release/0.13.9/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.13.9/master` into `master` to tag the release.
--- …
=> Release 0.13.9

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.14.1.
Notes:
- This PR targets `release/0.14.1/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.14.1/master` into `master` to tag the release.
--- …
=> Release 0.14.1

CHANGES.rst, MatrixKit/Models/MXKAppSettings.h, MatrixKit/Models/MXKAppSettings.m
fix https://github.com/vector-im/element-ios/issues/4075
comments from https://github.com/matrix-org/matrix-ios-kit/pull/762#pullrequestreview-586372393 are applied as well.
=> Pre share session keys when typing by default

CHANGES.rst, MatrixKit/Models/Account/MXKAccount.m
Fix vector-im/element-ios/issues/4073
I do not like this fix. I think we should fix it at the SDK level. We need to do much more cleaning like:
- Kit should not have a UIBackground task to manage the pause. It should be manage the sdk itself
- We should remove things related to `[MXSession backgroundSync:]` we have `MXBackgroundSyncService`
At least, this PR is doing the same thing as upper in this same method but it does it now for the particular case where the app is put in background while `MXSession` is doing its first sync (`MXSessionStateSyncInProgress`).
=> App state: Infinite loading spinner when resuming the app

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.14.4.
Notes:
- This PR targets `release/0.14.4/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.14.4/master` into `master` to tag the release.
--- …
=> Release 0.14.4

CHANGES.rst, MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKitTests/MXKRoomDataSource+Tests.h, MatrixKitTests/MXKRoomDataSource+Tests.m, MatrixKitTests/MXKRoomDataSourceTests.swift, MatrixKitTests/MatrixKitTests-Bridging-Header.h
Collapsible elements of the `bubbles` array form a doubly-linked list with strong references stored in `prevCollapsableCellData` and `nextCollapsableCellData`. This retain cycle prevents the bubbles from being deallocated even when the `bubbles` array itself is destroyed.
This is easy to reproduce on the Element iOS app:
1. Open a large room (e.g. [#main:postmarketos.org](https://matrix.to/#/#main:postmarketos.org))
2. Scroll up a few pages (new collapsed bubbles are added)
3. Tap back out of the room (the `MXKRoomDataSource` instance will be reset)
4. Fire up the memory graph debugger in Xcode
At this point, you'll notice orphaned chains of mutual strong references that cannot be deallocated.
The present fix breaks the strong reference cycle by nilifying both `prevCollapsableCellData` …
=> MXKRoomDataSource: Fix memory leak in doubly-linked bubble list

CHANGES.rst, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKitTests/MXKRoomDataSource+Tests.h, MatrixKitTests/MXKRoomDataSourceTests.swift
As reported in vector-im/element-ios#4102, membership changes are sometimes wrongly collapsed. This happens when events of the same collapsible series are processed in different batches. For forward directed events, only the start of a collapsible series is tracked in `collapsingCellDataSeriess`. As a result, when the event that corresponds to the beginning of the series was processed in a preceding event batch, the series will be missing in `collapsingCellDataSeriess` and its summary string won't get updated.
This commit fixes the situation by adding the start of the series to `collapsingCellDataSeriess` when it is missing and the series is appended to.
Signed-off-by: Johannes Marbach <n0-0ne+github@mailbox.org>
=> Fix collapsing of separately processed events

CHANGES.rst, MatrixKit/Controllers/MXKRoomViewController.h, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Controllers/MXKViewController.m
fix https://github.com/vector-im/element-ios/issues/4156
=> vertical padding is borked on new attachment UI after going into file selector and out again

CHANGES.rst, MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Models/Room/MXKRoomBubbleCellData.m, MatrixKit/Models/Room/MXKRoomBubbleCellDataStoring.h, MatrixKit/Utils/EventFormatter/MXKEventFormatter.h, MatrixKit/Utils/EventFormatter/MXKEventFormatter.m, MatrixKitTests/MXKEventFormatter+Tests.h, MatrixKitTests/MXKEventFormatterTests.m
As reported in vector-im/element-ios#4102, collapsed membership changes in the Element iOS app currently _always_ display the sender avatar. In contrast, the Element web app shows the avatar of the user whose membership has changed in this case.
This commit introduces new properties `targetId`, `targetDisplayName`, `targetAvatarUrl` and `targetAvatarPlaceholder` on `MXKRoomBubbleCellDataStoring`. The values are populated from the event (in case it is an `m.room.member` event) in the initializer of `MXKRoomBubbleCellData` (where the corresponding sender properties are already being assigned). This way, clients can easily choose to present the target avatar instead of the sender avatar when processing the bubble data.
Note that the "target" terminology was taken over from matrix-js-sdk …
=> MXKRoomBubbleCellDataStoring: Introduce target user ID, display name and avatar URL for room membership events

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.14.9.
Notes:
- This PR targets `release/0.14.9/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.14.9/master` into `master` to tag the release.
--- …
=> Release 0.14.9

CHANGES.rst, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile
This PR prepares the release of MatrixKit v0.14.10.
Notes:
- This PR targets `release/0.14.10/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.14.10/master` into `master` to tag the release.
--- …
=> Release 0.14.10

.github/workflows/ci.yml, CHANGES.rst, fastlane/Fastfile
Those GH actions check:
- pod lib lint
- tests
- Sample app build
BK checks are broken. I am going to disable it. 
The tests build is going to be fixed in the SDK with https://github.com/vector-im/element-ios/issues/4258. 
History is a bit useless. I needed to play to make fastlane `git_branch` lane work so that we can have a different behavior between release PRS and others.
Element-iOS GH actions will need to have this update.
=> CI: Introduce GH actions

CHANGES.rst, MatrixKit/Controllers/MXKAuthenticationViewController.h, MatrixKit/Controllers/MXKAuthenticationViewController.m
fix https://github.com/vector-im/element-ios/issues/4276
=> Expose current HTTP Operation in MXKAuthenticationViewController

CHANGES.rst, MatrixKit/Models/Account/MXKAccount.m
To be better understand what is happening in https://github.com/vector-im/element-ios/issues/3921#issuecomment-833517115
=> MXKAccount: Log reasons for incompatible sync filter

CHANGES.rst, MatrixKit/Models/Room/MXKRoomDataSource.m
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1091
Part of vector-im/element-ios#4306.
Decryptions are also no more required. They must be done upstream now from asynchronous operations.
=> MXKRoomDataSource: Decrypt unsent messages to follow MatrixSDK changes

CHANGES.rst, MatrixKit/Controllers/MXKCallViewController.m
Fix https://github.com/matrix-org/element-ios-rageshakes/issues/10045
=> Fix status text of a remotely held call

CHANGES.rst, MatrixKit/Models/Room/MXKAttachment.m
Part of vector-im/element-ios#4303
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1125
=> MXKAttachment: Adapt `mimetype` Changes

CHANGES.rst, MatrixKit/Utils/EventFormatter/MXKEventFormatter.m, MatrixKit/Utils/MXKTools.h
This adjusts the position of the emote prefix in the case of replies by looking for the end of the quoted parent content.
Fixes https://github.com/vector-im/element-ios/issues/4081
=> Fix display of emote replies

CHANGES.rst, MatrixKit.podspec, MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/MatrixKitVersion.m, MatrixKit/Models/Room/MXKAttachment.h, MatrixKit/Models/Room/MXKAttachment.m, MatrixKit/Models/Room/MXKRoomBubbleCellData.m, MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m, Podfile
This PR prepares the release of MatrixKit v0.15.2.
Notes:
- This PR targets `release/0.15.2/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.15.2/master` into `master` to tag the release.
--- …
=> Release 0.15.2

CHANGES.rst, MatrixKit/Controllers/MXKAuthenticationViewController.h
Adds `authenticationActivityIndicatorContainerView` outlet for https://github.com/vector-im/element-ios/pull/4491.
It seemed more logical to have this in `MXKAuthenticationViewController.h`, as it keeps it along side the `authenticationActivityIndicator` outlet.
=> Add authentication indicator container outlet.

CHANGES.rst, MatrixKit/Controllers/MXKRoomViewController.m, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.h, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m
Slow motion videos are returned from the photos picker as AVComposition objects.
- `sendVideo:` methods now take an `AVAsset` instead of an `NSURL`.
Part of https://github.com/vector-im/element-ios/pull/4541 along with https://github.com/matrix-org/matrix-ios-sdk/pull/1153
=> Add support for sending slow motion videos

MatrixKit/Models/Room/MXKAttachment.m, MatrixKit/Models/Room/MXKRoomDataSource.h, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKitTests/EncryptedAttachmentsTest.m
Fixes vector-im/element-ios/issues/4577 - Decrypt attachments on a background thread.
=> Decrypt attachments on a background thread.

CHANGES.rst, MatrixKit/Models/Account/MXKAccount.h, MatrixKit/Models/Account/MXKAccount.m
Added transient info storage dictionary on MXKAccount.
Fixes - vector-im/element-ios/issues/4578
=> Added transient info storage dictionary on MXKAccount.

CHANGES.rst, MatrixKit/Models/Room/MXKRoomDataSource.m
Fix vector-im/element-ios#4605
=> MXKRoomDataSource: Synchronized Access to `bubbles` on Pagination

MatrixKit/Models/RoomList/MXKRecentsDataSource.h, MatrixKit/Models/RoomList/MXKRecentsDataSource.m, MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.h, MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m
Handle https://github.com/vector-im/element-ios/issues/4509
Part of https://github.com/vector-im/element-ios/issues/4503
=> [Spaces] Show spaces in left panel #4509

MatrixKit/Models/Room/MXKRoomBubbleComponent.m, changelog.d/4510.bugfix
Fixes https://github.com/vector-im/element-ios/issues/4510 by ignoring reaction events when computing whether to show a warning badge.
From what I can tell, the cell data for the point in time when a reaction was sent would be wanting to show the encryption badge but without a component to show it, so would appear to be randomly indented.
=> Fix timeline alignment bug

MatrixKit/Models/Account/MXKAccount.m, MatrixKit/Models/MXKAppSettings.h, MatrixKit/Models/MXKAppSettings.m, changelog.d/4132.change
Part of https://github.com/vector-im/element-ios/pull/4662.
- Adds `notificationBodyLocalizationKey` to `MXKAppSettings` to customise the default notification payload.
=> Add notificationBodyLocalizationKey to MXKAppSettings.

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/Utils/MXKTools.h, MatrixKit/Utils/MXKTools.m, MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m, changelog.d/4638.feature
Part of https://github.com/vector-im/element-ios/issues/4638 along with the PR https://github.com/vector-im/element-ios/pull/4721.
Additionally tweaks the strings used in the image compression mode prompt, and uses https://github.com/matrix-org/matrix-ios-sdk/pull/1218 for an updated file size string.
=> Add +videoConversionPromptForVideoAsset:withCompletion: to MXKTools.

MatrixKit/Models/Account/MXKAccount.m, changelog.d/4834.change
Fix vector-im/element-ios#4834
=> MXKAccount: Use `pauseable` property of MXSession

MatrixKit/Models/MXKAppSettings.h, MatrixKit/Models/MXKAppSettings.m, changelog.d/4826.bugfix
Fixes https://github.com/vector-im/element-ios/issues/4826. The matrix.to host was only stored in the synthesized variable and not the user defaults.
This returns matrix.to when the user defaults return `nil` and always sets `@[]` instead of `nil`, to match the desirable behaviour discussed [here](https://github.com/matrix-org/matrix-ios-kit/pull/893#discussion_r704513073).
=> Revert removal of default ignored hosts value.

MatrixKit.xcodeproj/project.pbxproj, MatrixKit/Models/Room/MXKRoomBubbleCellData.h, MatrixKit/Models/Room/MXKRoomBubbleCellData.m, MatrixKit/Models/Room/MXKRoomBubbleCellDataStoring.h, MatrixKit/Models/Room/MXKRoomBubbleCellDataWithAppendingMode.m, MatrixKit/Models/Room/MXKRoomBubbleComponent.h, MatrixKit/Models/Room/MXKRoomDataSource.m, MatrixKit/Models/Room/MXKURLPreviewDataProtocol.h, changelog.d/4896.change
Fixes https://github.com/vector-im/element-ios/issues/4896 along side the PR https://github.com/vector-im/element-ios/pull/4924. This PR makes 2 changes:
Adds `invalidateTextLayout` method to `MXKRoomBubbleCellData` and replaces all occurrences of setting the attributed string to nil with this method. This was done to make updating the cell's layout more obvious. Any tweaks to the docs/naming totally welcome 🙂
Adds `urlPreviewData` and `showURLPreview` properties to `MXKBubbleComponent` for use from Element (they do nothing by theirselves in Kit). There is one question/comment inline about how this was done.
=> Use attributed string whitespace for URL previews.

CHANGES.md, MatrixKit.podspec, MatrixKit/MatrixKitVersion.m, Podfile, changelog.d/x-nolink-0.change
This PR prepares the release of MatrixKit v0.16.4.
Notes:
- This PR targets `release/0.16.4/master`, which has been cut from `master`.
to use the now officially released dependencies -- before ultimately merging `release/0.16.4/master` into `master` to tag the release.
--- …
=> Release 0.16.4

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings, MatrixKit/Controllers/MXKAuthenticationViewController.m, MatrixKit/Controllers/MXKAuthenticationViewController.xib, MatrixKit/Models/Account/MXKAccount.m, MatrixKit/Models/Contact/MXKContactManager.m, changelog.d/857.misc
This PR standardises the spelling and casing of the following terms, across the codebase, as per vector-im/element-ios#2655:
- homeserver
- identity server
- integration manager
While the issue mentions only user-visible text, this PR changes all instances of the terms, regardless of whether they're user-visible or not. I think there's value in standardising these terms even in non-user-visible text, so I went ahead and applied the changes to all text.
For reference, here's the script I used to find candidates for replacement: https://gist.github.com/psrpinto/b3787bae212d5d99649b517e2efd4dce
Related to vector-im/element-ios#4559
=> Standardise casing of identity server

MatrixKit/Models/Room/MXKRoomDataSource.m, changelog.d/4950.bugfix
Fixes https://github.com/vector-im/element-ios/issues/4950 and likely issues like https://github.com/vector-im/element-ios/issues/4564 although I'm unsure how to reliably reproduce those kind of things.
Both `updateCellDataReactions:forEventId:` and `updateCellData:forEditionWithReplaceEvent:andEventId:` indicate that the text layout needs recomputing, but `updateCellData:withReadReceipts:forEventId:` did not.
=> Fix cell height when read receipts update.

MatrixKit/Models/Account/MXKAccount.h, MatrixKit/Models/Account/MXKAccount.m, changelog.d/4519.api
Following on from https://github.com/vector-im/element-ios/pull/4530 this removes `showDecryptedContentInNotifications` from `MXKAccount` as it is no longer used.
=> Tidy up following on from element-ios#4530

MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
This PR makes threaded events look like regular replies.
`<blockquote>` css does not handle background color for these _replies_, i'll address this issue later.
Fixes vector-im/element-ios#5007
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1272
=> Threads P0

MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m, changelog.d/4893.feature
Needed for https://github.com/vector-im/element-ios/issues/4893
=> Support pagination in the Space Summary API

MatrixKit/Models/Room/MXKRoomDataSource.m, changelog.d/4701.bugfix
Fixes https://github.com/vector-im/element-ios/issues/4071
I think we can remove this check altogether @ismailgulek. 
It was introduced in an [attempt to fix an issue](https://github.com/matrix-org/matrix-ios-kit/pull/674) with notifications not going to the message. But we no longer [highlight messages from notifications](https://github.com/vector-im/element-ios/pull/3341).
In the codes current state, I don't think this check is having any effect(maybe it did in the past) other than causing a delay in the join.
At the moment it's just called for the "jump to unread" button and when joining a room with an initialEventId, in both cases we are starting the timeline at a point in the past.
When we start the timeline at an event in the past [we load an in memory event …
=> Fix unresponsive "Jump to unread"

MatrixKit/Views/RoomTitle/MXKRoomTitleView.m, changelog.d/pr-951.bugfix
This was creating a *lot* of noise in the logs:
> ⚠️ [MXStrongifyAndReturnIfNil] Released reference at MXKRoomTitleView.m:128
=> Remove room summary observer on MXKRoomTitleView.

MatrixKit.podspec, MatrixKit/Categories/MXEvent+MatrixKit.h, MatrixKit/Categories/NSBundle+MatrixKit.h, MatrixKit/Controllers/MXKRecentListViewController.m, MatrixKit/MatrixKit.h, MatrixKit/Models/RoomList/MXKRecentCellData.h, MatrixKit/Models/RoomList/MXKRecentCellData.m, MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.h, MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m, Samples/MatrixKitSample/MXKSampleJSQMessagesViewController.m, changelog.d/5194.bugfix
Part of https://github.com/vector-im/element-ios/issues/5194
=> Improve generated Swift header imports

MatrixKit/Models/Room/MXKRoomDataSource.m, changelog.d/5203.bugfix
Fixes https://github.com/vector-im/element-ios/issues/5203
=> Fix crash during late-decryption of timeline events with attachments.
