MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Models/MXKAppSettings.h
MatrixKit/Models/MXKAppSettings.m
MatrixKit/Models/Room/MXKRoomBubbleComponent.m
MatrixKit/Models/RoomList/MXKRecentCellData.m
MatrixKit/Utils/MXKEventFormatter.h
MatrixKit/Utils/MXKEventFormatter.m
Podfile.lock

This will allow Chrome to be set to the default link handler in
applications of they want. And probably other browsers too.

Allow URL scheme of links to be customized

---

MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Controllers/MXKCallViewController.m
MatrixKit/Controllers/MXKRoomAttachmentsViewController.m
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Utils/MXKLRUCache.h
MatrixKit/Utils/MXKLRUCache.m
MatrixKit/Utils/Media/MXKMediaManager.h
MatrixKit/Utils/Media/MXKMediaManager.m
MatrixKit/Views/Account/MXKAccountTableViewCell.m
MatrixKit/Views/MXKImageView.h
MatrixKit/Views/MXKImageView.m
MatrixKit/Views/MXKReceiptAvartarsContainer.m
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
MatrixKit/Views/RoomMemberList/MXKRoomMemberTableViewCell.m

-> The member avatars are cached
-> the 0.5s blank screen while opening a room should be removed.

Room launch improvement

---

MatrixKit/Models/Contact/MXKContactManager.m
MatrixKit/Models/Room/MXKRoomDataSource.m

Implement joinRoom action in case of server sync v2 use.

MXSession: V2 sync joining.

---

MatrixKit/Models/Room/MXKRoomDataSource.h
MatrixKit/Models/Room/MXKRoomDataSource.m

Did some refactoring according to Xcode profiler.
Tested when doing a big app resuming.

Performance profiling

---

MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Controllers/MXKRoomSettingsViewController.h
MatrixKit/Controllers/MXKRoomSettingsViewController.m
MatrixKit/Controllers/MXKRoomSettingsViewController.xib
MatrixKit/MatrixKit.h

MXKRoomDetailsViewController becomes MXKRoomSettingsViewController

Room settings view controller v2

---

MatrixKit/Models/RoomList/MXKRecentsDataSource.h
MatrixKit/Models/RoomList/MXKRecentsDataSource.m

Add the recents cell swipe menu (i.e. favorites, mute and leaving actions)

Recents swipe actions2

---

MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Views/MXKCollectionViewCell/MXKCollectionViewCell.h
MatrixKit/Views/MXKCollectionViewCell/MXKCollectionViewCell.m
MatrixKit/Views/MXKCollectionViewCell/MXKMediaCollectionViewCell.h

Add MXKCollectionViewCell class to define custom UICollectionViewCell.

MXKDataSource refactoring

---

MatrixKit/Models/RoomList/MXKRecentsDataSource.h
MatrixKit/Models/RoomList/MXKRecentsDataSource.m

If there is already a rule for this room, it is now deleted before creating a new "don't notify" one.

muteRoomNotifications :

---

MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m

Manage the kMXSessionInvitedRoomsDidChangeNotification events

add_invite_room_section

---

MatrixKit/Views/MXKReceiptSendersContainer.m

Adjust 'more' label position according to its actual width

Read receipts layout

---

MatrixKit/Models/Contact/MXKContactManager.h
MatrixKit/Models/Contact/MXKContactManager.m
MatrixKit/Utils/MXKTools.h
MatrixKit/Utils/MXKTools.m

Update the contacts creation management
a dedicated mode is created

room_members_search

---

MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Controllers/MXKSearchViewController.h
MatrixKit/Controllers/MXKSearchViewController.m
MatrixKit/Controllers/MXKSearchViewController.xib
MatrixKit/MatrixKit.h
MatrixKit/Models/Search/MXKSearchCellData.h
MatrixKit/Models/Search/MXKSearchCellData.m
MatrixKit/Models/Search/MXKSearchCellDataStoring.h
MatrixKit/Models/Search/MXKSearchDataSource.h
MatrixKit/Models/Search/MXKSearchDataSource.m
MatrixKit/Views/Search/MXKSearchTableViewCell.h
MatrixKit/Views/Search/MXKSearchTableViewCell.m
MatrixKit/Views/Search/MXKSearchTableViewCell.xib
Samples/MatrixKitSample/Base.lproj/Main.storyboard
Samples/MatrixKitSample/MXKSampleMainTableViewController.m

Added MXKSearchViewController, a VC to search messages in one room or in all user's rooms.

Search api support

---

MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKRoomDataSource.m

Most of the job is done in the sdk. see https://github.com/matrix-org/matrix-ios-sdk/pull/62

SYIOS-183 Store in-progress messages

---

MatrixKit/Models/Room/MXKRoomDataSource.m
MatrixKit/Views/MXKEventDetailsView.m
Podfile.lock

Follow changes due to https://github.com/matrix-org/matrix-ios-sdk/pull/69

Remove Mantle

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Models/Contact/MXKContact.h
MatrixKit/Models/Contact/MXKContact.m
MatrixKit/Models/Room/MXKRoomDataSource.m
MatrixKit/Utils/MXKEventFormatter.m

Added management of m.room.third_party_invite events.

Email invitation

---

MatrixKit/Controllers/MXKRoomMemberDetailsViewController.m
MatrixKit/Controllers/MXKRoomSettingsViewController.m
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKRoomDataSource.m
MatrixKit/Models/RoomMemberList/MXKRoomMemberListDataSource.m
MatrixKit/Views/RoomTitle/MXKRoomTitleView.m
MatrixKit/Views/RoomTitle/MXKRoomTitleViewWithTopic.m

Changes due to https://github.com/matrix-org/matrix-ios-sdk/pull/78

Updated to support MXEventTimeline

---

MatrixKit/Controllers/MXKRoomViewController.h
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Controllers/MXKSearchViewController.m
MatrixKit/Models/Room/MXKRoomBubbleCellData.h
MatrixKit/Models/Room/MXKRoomDataSource.h
MatrixKit/Models/Room/MXKRoomDataSource.m
MatrixKit/Models/RoomList/MXKRecentCellData.m
MatrixKit/Models/Search/MXKSearchDataSource.m

and fix things to make the display of a timeline from a search result work.

Let MXKRoomViewController display a timeline from the past

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Controllers/MXKAccountDetailsViewController.h
MatrixKit/Controllers/MXKAccountDetailsViewController.m
MatrixKit/Models/Account/MXKAccount.h
MatrixKit/Models/Account/MXKAccount.m
MatrixKit/Models/MXK3PID.h
MatrixKit/Models/MXK3PID.m

This PR updates the email validation flow.

New email bind

---

MatrixKit/Models/Contact/MXKContactManager.h
MatrixKit/Models/Contact/MXKContactManager.m

Include address book emails in search result.

Fix vector-ios #196.

---

MatrixKit/Controllers/MXKRoomViewController.h
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKRoomDataSource.m

- Add 'autoJoinInvitedRoom' property to enable/disable auto join on invitation.
- Patch room data source to disable bubbles display on room preview.

mMXKRoomViewController: Prepare room preview support

---

MatrixKit/Controllers/MXKRoomViewController.h
MatrixKit/Controllers/MXKRoomViewController.m

to join a room from a 3PID invitation or room link.

MXKRoomViewController: Added "joinRoomWithRoomId:andSignUrl:"

---

MatrixKit/Controllers/MXKAuthenticationViewController.h
MatrixKit/Controllers/MXKAuthenticationViewController.m
MatrixKit/Models/MXK3PID.h
MatrixKit/Models/MXK3PID.m
MatrixKit/Views/Authentication/MXKAuthInputsView.h

Bug Fix: https://github.com/vector-im/vector-ios/issues/240

MXKAuthenticationViewController: Fix registration cancellation

---

MatrixKit/Controllers/MXKAttachmentsViewController.m
MatrixKit/Models/Room/MXKAttachment.h
MatrixKit/Models/Room/MXKAttachment.m
MatrixKit/Models/Room/MXKRoomDataSource.m

https://github.com/vector-im/vector-ios/issues/237

mBugFix - Chat screen: wrong attachment is opened.

---

MatrixKit/Models/Room/MXKRoomDataSource.m

https://github.com/vector-im/vector-ios/issues/254

Bug Fix: Wrong application icon badge number

---

MatrixKit/Models/RoomList/MXKInterleavedRecentsDataSource.m
MatrixKit/Models/RoomList/MXKRecentsDataSource.m
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.h
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
MatrixKit/Views/RoomBubbleList/MXKRoomIOSOutgoingBubbleTableViewCell.m
MatrixKit/Views/RoomBubbleList/MXKRoomIncomingBubbleTableViewCell.m
MatrixKit/Views/RoomBubbleList/MXKRoomOutgoingAttachmentBubbleCell.m
MatrixKit/Views/RoomBubbleList/MXKRoomOutgoingBubbleTableViewCell.m
MatrixKit/Views/RoomList/MXKInterleavedRecentTableViewCell.m
MatrixKit/Views/RoomList/MXKRecentTableViewCell.h
MatrixKit/Views/RoomList/MXKRecentTableViewCell.m

We report the delegate in recent table view cell in order to handle user's actions observed in the cell, like button press or tap gestures.

MXKRecentTableViewCell: Support user's action on recent cell.

---

MatrixKit/Controllers/MXKRoomViewController.m

https://github.com/vector-im/vector-ios/issues/268

BugFix: 6+/iPad: Better manage user with no room in landscape

---

MatrixKit/Controllers/MXKAttachmentsViewController.m

https://github.com/vector-im/vector-ios/issues/266

Chat screen: BF #266: Video playback stops when you rotate the device

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Controllers/MXKRoomMemberDetailsViewController.h
MatrixKit/Controllers/MXKRoomMemberDetailsViewController.m
MatrixKit/Controllers/MXKRoomViewController.h
MatrixKit/Controllers/MXKRoomViewController.m

https://github.com/vector-im/vector-ios/issues/295

Report abuse and ignore user

---

MatrixKit/Models/Account/MXKAccount.m

https://github.com/vector-im/vector-ios/issues/311

Bug Fix: all blank after upgrade; no spinner

---

MatrixKit/Controllers/MXKRoomViewController.h
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.h
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
MatrixKit/Views/RoomBubbleList/MXKRoomIncomingAttachmentBubbleCell.xib
MatrixKit/Views/RoomBubbleList/MXKRoomIncomingTextMsgBubbleCell.xib

https://github.com/vector-im/vector-ios/issues/309

BugFix: It's too hard to press names to auto-insert nicks

---

MatrixKit/Models/Account/MXKAccount.m

https://github.com/vector-im/vector-ios/issues/247

Detect when the access token is no more valid

---

MatrixKit/Models/Account/MXKAccount.m
MatrixKit/Models/Account/MXKAccountManager.m

https://github.com/vector-im/vector-ios/issues/333

Need to check push notification registration

---

MatrixKit/Models/Room/MXKRoomBubbleCellData.m
MatrixKit/Models/Room/MXKRoomDataSource.m

https://github.com/vector-im/vector-ios/issues/380

Bug Fix:Room screen: Tap on attached video does nothing

---

MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKRoomDataSourceManager.m

- Remove text input field in case of peeking
- Release correclty the room data source when room view controller has the ownership.

Room Peeking support

---

MatrixKit/Controllers/MXKRoomViewController.h
MatrixKit/Controllers/MXKRoomViewController.m

https://github.com/vector-im/vector-ios/issues/223

Added missing slash commands: /invite, /part and /topic

---

MatrixKit.podspec
MatrixKit/Models/Room/MXKRoomDataSource.m
MatrixKit/Utils/MXKEventFormatter.h
MatrixKit/Utils/MXKEventFormatter.m
Podfile

https://github.com/matrix-org/matrix-ios-kit/issues/124
It uses GHMarkdownParser (https://github.com/OliverLetterer/GHMarkdownParser) which license is MIT.

Markdown typing support

---

MatrixKit/Utils/MXKEventFormatter.m

https://github.com/vector-im/vector-ios/issues/423

BF: MXKEventFormatter: MD swallows leading #'s even if there are less than 3

---

MatrixKit/Models/Room/MXKRoomBubbleCellData.m

https://github.com/vector-im/vector-ios/issues/437

HTML blockquote is badly rendered: some characters can miss

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.h
MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m

https://github.com/vector-im/vector-ios/issues/301

Allow multi selection of pictures

---

MatrixKit/Categories/MXEvent+MatrixKit.h
MatrixKit/Categories/MXEvent+MatrixKit.m
MatrixKit/Controllers/MXKRoomMemberDetailsViewController.m
MatrixKit/Controllers/MXKRoomSettingsViewController.m
MatrixKit/Models/Room/MXKRoomDataSource.m
MatrixKit/Views/MXKEventDetailsView.m

Redacting membership events should immediately reset the displayname & avatar of room members

Vector 443

---

MatrixKit/Controllers/MXKCallViewController.m

https://github.com/vector-im/vector-ios/issues/521
- Handle correctly headset usage

Bug Fix - Screen still tries to turn off when on a VC

---

MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKRoomDataSource.m
MatrixKit/Models/Room/MXKRoomDataSourceManager.h
MatrixKit/Models/Room/MXKRoomDataSourceManager.m

MXKRoomViewController: mark all messages as read for the displayed room.

MXKRoomDataSourceManager: Add API to mark all messages as read.

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Controllers/MXKRoomViewController.h
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKRoomDataSource.h
MatrixKit/Models/Room/MXKRoomDataSource.m

https://github.com/vector-im/vector-ios/issues/484

Handle 404 (Event not found) on permalinks

---

MatrixKit/Controllers/MXKRoomViewController.h
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKRoomDataSource.m

https://github.com/vector-im/vector-ios/issues/532
MXKRoomViewController: acknowledge automatically the most recent event visible in table view.

Bug Fix - Chat screen: New message(s) notification

---

MatrixKit/Controllers/MXKAttachmentsViewController.m

https://github.com/vector-im/vector-ios/issues/460

Bug fix: Attachment viewer: Video controls are buggy

---

MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.h
MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m
MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarViewWithHPGrowingText.m
MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarViewWithSimpleTextView.m

https://github.com/vector-im/vector-ios/issues/385

Room screen: mention the member name at the cursor position (not a the end)

---

MatrixKit/Models/Account/MXKAccount.m

https://github.com/vector-im/vector-ios/issues/552

Bug fix: Locking phone whilst setting up a call interrupts the call setup

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Models/Contact/MXKContactManager.h
MatrixKit/Models/Contact/MXKContactManager.m
MatrixKit/Models/MXKAppSettings.h
MatrixKit/Models/MXKAppSettings.m
MatrixKit/Utils/MXKTools.h
MatrixKit/Utils/MXKTools.m

https://github.com/vector-im/vector-ios/issues/551

Warn explicitly that your addressbook's emails are uploaded for discovering matrix IDs if you enable that permission

---

MatrixKit/Controllers/MXKRoomViewController.m

https://github.com/vector-im/vector-ios/issues/600

Bug Fix - Chat screen: unexpected scroll up on new sent messages

---

MatrixKit/Controllers/MXKCallViewController.m

https://github.com/vector-im/vector-ios/issues/631

No ringback tones when placing voice calls in silent mode

---

MatrixKit/Utils/MXKEventFormatter.m

https://github.com/vector-im/vector-ios/issues/643

Bug Fix - The room preview does not always display the right member info

---

MatrixKit/Models/Room/MXKAttachment.m

We should support mxc URLs and only msc URLs, rather than
making requests to random servers which leave us vulnerable to web
bugs.

Don't fall back on the raw URL

---

MatrixKit/Controllers/MXKAttachmentsViewController.m
MatrixKit/Models/Room/MXKAttachment.h
MatrixKit/Models/Room/MXKAttachment.m
MatrixKit/Utils/MXKEventFormatter.m
MatrixKit/Utils/Media/MXKMediaManager.h
MatrixKit/Utils/Media/MXKMediaManager.m
MatrixKit/Views/MXKImageView.h
MatrixKit/Views/MXKImageView.m
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m

Not the full attachment content yet though

Support for displaying encrypted thumbnails

---

MatrixKit/Controllers/MXKAttachmentsViewController.m
MatrixKit/Models/Room/MXKRoomDataSource.m

Also:
* Send encrypted videos with corrfect msgtype
* Missed moving thumbnail_file to info in a couple of places

Support playback of encrypted videos

---

MatrixKit/Models/Room/MXKAttachment.m
MatrixKit/Models/Room/MXKRoomDataSource.m

* Fixes sending of encrypted attachments (info dict was immutable)
* Fixes saving of attachments (the saving happened asynchronously so we deleted the file before the saving happened)

Merge E2E release branch back into develop

---

MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/MatrixKit.h
MatrixKit/Views/DeviceView/MXKDeviceView.h
MatrixKit/Views/DeviceView/MXKDeviceView.m
MatrixKit/Views/DeviceView/MXKDeviceView.xib
MatrixKit/Views/EncryptionInfoView/MXKEncryptionInfoView.h
MatrixKit/Views/EncryptionInfoView/MXKEncryptionInfoView.m
MatrixKit/Views/EncryptionInfoView/MXKEncryptionInfoView.xib

to display device or encryption information.

Device/Encryption: Add MXKDeviceView and MXKEncryptionInfoView

---

MatrixKit/Models/Room/MXKRoomBubbleCellData.m
MatrixKit/Models/Room/MXKRoomBubbleCellDataStoring.h
MatrixKit/Models/Room/MXKRoomDataSource.m

This is done on kMXEventDidDecryptNotification (https://github.com/matrix-org/matrix-ios-sdk/pull/186)
Port of https://github.com/matrix-org/matrix-react-sdk/pull/556

Crypto: Update the display of encrypted events when they are lately decrypted

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Utils/MXKEventFormatter.m

(specially for unknown inbound session id)

Crypto: Improve decryption error messages 

---

MatrixKit/Categories/MXEvent+MatrixKit.h
MatrixKit/Categories/MXEvent+MatrixKit.m
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKRoomBubbleCellDataStoring.h
MatrixKit/Models/Room/MXKRoomBubbleComponent.h
MatrixKit/Models/Room/MXKRoomBubbleComponent.m
MatrixKit/Models/Room/MXKRoomDataSource.m
MatrixKit/Models/RoomList/MXKRecentCellData.m
MatrixKit/Utils/MXKEventFormatter.m
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
MatrixKit/Views/RoomBubbleList/MXKRoomOutgoingAttachmentBubbleCell.m
MatrixKit/Views/RoomBubbleList/MXKRoomOutgoingBubbleTableViewCell.m

The category `MXEvent+MatrixKit` handles now:
- the potential error during the event formatting.
and
- the highlighted mode of the event.

Report the MXEvent changes.

---

MatrixKit/Views/EncryptionInfoView/MXKEncryptionInfoView.m

Changes related to  https://github.com/matrix-org/matrix-ios-sdk/pull/204

Crypto threading: Follow changes in the sdk

---

MatrixKit/Models/Contact/MXKContact.h
MatrixKit/Models/Contact/MXKContact.m
MatrixKit/Models/Contact/MXKContactManager.h
MatrixKit/Models/Contact/MXKContactManager.m

Prepare https://github.com/vector-im/riot-ios/issues/904

Local contacts methods

---

MatrixKit/Models/Account/MXKAccount.m

https://github.com/vector-im/riot-ios/issues/963

Bug Fix: App is stuck on logout when device is offline.

---

MatrixKit/Models/Room/MXKRoomDataSource.m

https://github.com/vector-im/riot-ios/issues/1007

Bug Fix - Local echoes for typed messages stay (far) longer in grey

---

MatrixKit/Models/Contact/MXKContact.h
MatrixKit/Models/Contact/MXKContact.m
MatrixKit/Models/Contact/MXKContactField.h
MatrixKit/Models/Contact/MXKContactManager.m
MatrixKit/Models/Contact/MXKPhoneNumber.h
MatrixKit/Models/Contact/MXKPhoneNumber.m

https://github.com/vector-im/riot-ios/issues/904
- Discover matrix users by using msisdn

Improve the people invite screens

---

MatrixKit/Views/DeviceView/MXKDeviceView.h
MatrixKit/Views/DeviceView/MXKDeviceView.m
MatrixKit/Views/DeviceView/MXKDeviceView.xib

https://github.com/vector-im/riot-ios/issues/1059

Bug Fix - Device information modal broken

---

MatrixKit/Models/Contact/MXKPhoneNumber.m

- Remove whitespace in search pattern

Improve search by phone number

---

MatrixKit/Controllers/MXKAttachmentsViewController.m
MatrixKit/Views/MXKCollectionViewCell/MXKMediaCollectionViewCell.m

Solution for this [issue](https://github.com/vector-im/riot-ios/issues/919)

Stop playing any video on disappearing of MXKAttachmentsViewController

---

MatrixKit/Controllers/MXKAuthenticationViewController.m

https://github.com/vector-im/riot-ios/issues/1103

Bug Fix - Riot user created without msisdn in his settings

---

MatrixKit/Controllers/MXKAttachmentsViewController.m
MatrixKit/Views/MXKCollectionViewCell/MXKMediaCollectionViewCell.m

https://github.com/vector-im/riot-ios/issues/1109

Bug Fix - Image viewer repeatedly loses overlay menu

---

MatrixKit/Controllers/MXKAttachmentsViewController.m

https://github.com/vector-im/riot-ios/issues/1143

Bug Fix -  App crashes after using the attachment viewer

---

MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m

https://github.com/vector-im/riot-ios/issues/1144

BF: Search in local rooms is broken since MXRoomSummary

---

MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Models/PublicRoomList/DirectoryServerList/MXKDirectoryServerCellData.h
MatrixKit/Models/PublicRoomList/DirectoryServerList/MXKDirectoryServerCellData.m
MatrixKit/Models/PublicRoomList/DirectoryServerList/MXKDirectoryServerCellDataStoring.h
MatrixKit/Models/PublicRoomList/DirectoryServerList/MXKDirectoryServersDataSource.h
MatrixKit/Models/PublicRoomList/DirectoryServerList/MXKDirectoryServersDataSource.m

Add directory server list data model (datasource, cellDataStoring protocol and its minimal implementation)
There in no views and the VC. They will be directly coded in Riot project.

Directory server list

---

MatrixKit/Controllers/MXKRecentListViewController.h
MatrixKit/Controllers/MXKRecentListViewController.m
MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m

into the MXKSessionRecentsDataSource

MXKRecentListViewController: move the direct rooms listener

---

MatrixKit/Models/Room/MXKRoomDataSource.m

whereas the notification count was changed

MXKRoomDataSource: kMXKRoomDataSourceMetaDataChanged was not posted

---

MatrixKit/Controllers/MXKRecentListViewController.m

- Update the pull to kick mechanism to take into account some recents table view settings (used in inherited class).

MXKRecentsViewController

---

MatrixKit/Controllers/MXKContactListViewController.h
MatrixKit/Controllers/MXKContactListViewController.m
MatrixKit/Controllers/MXKRecentListViewController.h
MatrixKit/Controllers/MXKRecentListViewController.m
MatrixKit/Controllers/MXKSearchViewController.h
MatrixKit/Controllers/MXKSearchViewController.m

- Improve the search option handling in navigation bar.

Prepare UX Rework

---

MatrixKit.podspec
MatrixKit/Categories/NSBundle+MatrixKit.m
MatrixKit/Views/MXKCollectionViewCell/MXKCollectionViewCell.m
MatrixKit/Views/MXKTableViewCell/MXKTableViewCell.m

As recommended by Cocoapods https://guides.cocoapods.org/syntax/podspec.html#resource_bundles
Moreover, in a swift project, the assets are not retrieved if the bundle is not handle this way

Use bundle ressource to store assets

---

MatrixKit/Controllers/MXKRecentListViewController.m

- The search input view should appear like in the email client, stuck to the top of the table.
https://github.com/vector-im/riot-ios/issues/1194

Improve tab filter

---

MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m

https://github.com/vector-im/riot-ios/issues/1025
Add a sanity check to avoid empty array

Fix Photo selection and sending crash

---

MatrixKit/Controllers/MXKRoomViewController.m

https://github.com/vector-im/riot-ios/issues/553

Bug Fix - A permalink is positioned off the screen

---

MatrixKit/Controllers/MXKRoomViewController.m

https://github.com/matrix-org/riot-ios-rageshakes/issues/37

Bug Fix: Crashed when clicking on "jump to first unread"

---

MatrixKit/Controllers/MXKCallViewController.m

Now things work according to scheme from [1101](https://github.com/vector-im/riot-ios/issues/1101)

Fix for issue 1101

---

MatrixKit/Models/MXKAppSettings.h
MatrixKit/Models/MXKAppSettings.m

Update MXAppSettings with a new setting value for CallKit

---

MatrixKit/Controllers/MXKCallViewController.m

Update method calls in MXKCallViewController

---

MatrixKit/Controllers/MXKCallViewController.h
MatrixKit/Controllers/MXKCallViewController.m

Add playRingtone property

---

MatrixKit/Views/MXKImageView.m

Cell reuse bug on room list screen?
Yes I confirm this was the pb.
https://github.com/vector-im/riot-ios/issues/1124

Bug Fix: Room with no icon ended up with the icon of a different room.

---

Podfile
Podfile.lock

https://github.com/vector-im/riot-ios/issues/1365

MXKEventFormatter: Fix URLs with 2 hashes create wrong links

---

AUTHORS.rst
MatrixKit/Assets/MatrixKitAssets.bundle/nl.lproj
MatrixKit/Assets/MatrixKitAssets.bundle/nl.lproj/MatrixKit.strings

Note: I have not compiled the file to test if there weren't any errors.
Signed-off-by: Nathan van Beelen

Dutch translation of the strings

---

MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKAttachment.m
MatrixKit/Models/Room/MXKRoomBubbleCellData.m
MatrixKit/Utils/MXKEventFormatter.m
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
MatrixKit/Views/RoomBubbleList/MXKRoomIOSOutgoingBubbleTableViewCell.m

We support here the display of the attached audio files, but we are still not able to attach audio file.
https://github.com/vector-im/riot-ios/issues/1102

Bug Fix: Add the m.audio attachments support.

---

MatrixKit/Controllers/MXKAttachmentsViewController.m
MatrixKit/Controllers/MXKRoomViewController.h
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Controllers/MXKTableViewController.m
MatrixKit/Controllers/MXKViewController.m
MatrixKit/Views/MXKImageView.h
MatrixKit/Views/MXKImageView.m
MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.h
MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m

Handle correctly the status bar visibility (use the default UIViewController-based status bar system).
https://github.com/vector-im/riot-meta/issues/22

Prepare Dark theme

---

MatrixKit/Views/MXKImageView.m
MatrixKit/Views/MXKView.h
MatrixKit/Views/MXKView.m

Note: This was a regression introduced during the dark theme changes

Bug Fix - Wrong content mode is used to preview images

---

MatrixKit/Models/Account/MXKAccountManager.h
MatrixKit/Models/Account/MXKAccountManager.m

MXKAccountManager: Add a method to reload existing accounts

---

MatrixKit/Models/Account/MXKAccount.h
MatrixKit/Models/Account/MXKAccount.m

Connected with [#1469](https://github.com/vector-im/riot-ios/pull/1469)

Add showDecryptedContentInNotifications property to MXKAccount

---

MatrixKit/Controllers/MXKCallViewController.h
MatrixKit/Controllers/MXKCallViewController.m

Add support for incoming calls view

---

MatrixKit/Models/MXKAppSettings.h
MatrixKit/Models/MXKAppSettings.m

in order to customise supported events

MXKAppSettings: Add addSupportedEventTypes and removeSupportedEventTypes

---

MatrixKit/Models/Account/MXKAccount.h
MatrixKit/Models/Account/MXKAccount.m
MatrixKit/Models/Account/MXKAccountManager.h
MatrixKit/Models/Account/MXKAccountManager.m

independently of APNS settings.

MXKAccountManager/MXKAccount: Handle PushKit settings

---

MatrixKit/Animators/MXKAttachmentInteractionController.m

https://github.com/matrix-org/riot-ios-rageshakes/issues/334]
The issue occurred several times.

BF: Crash in [MXKAttachmentInteractionController finishInteractiveTransition]

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Controllers/MXKAuthenticationViewController.h
MatrixKit/Controllers/MXKAuthenticationViewController.m

https://github.com/vector-im/riot-ios/issues/910

Bug Fix - Device name leaks personal information

---

MatrixKit/Views/RoomTitle/MXKRoomTitleView.m

https://github.com/vector-im/riot-ios/issues/1569

Bug Fix - Once I changed my room title it is not updating in the room

---

MatrixKit/Models/Room/MXKRoomDataSource.m

They are likely to trip up many things later,
including our own C-based Markdown-to-HTML convertor.
Normally, we don't expect people to be entering NULL bytes in
messages, but because of a bug in iOS 11, it's easy to have it happen.
iOS 11's Smart Punctuation feature "conveniently" converts double
hyphens (`--`) to longer en-dashes (`—`).
However, when adding any kind of dash/hyphen after such an
en-dash, iOS would also insert a NULL byte inbetween the dashes
(`<en-dash>NULL<some other dash>`).
Even if a future iOS update fixes this, we'd better be defensive
and always remove occurrences of NULL bytes from text messages.
Signed-off-by: Slavi Pantaleev <s.pantaleev@gmail.com>

Remove NULL bytes from text messages

---

Samples/MatrixKitSample/MXKSampleJSQMessagesViewController.h

Fix some build warnings that popped up in Riot iOS.

---

MatrixKit/Models/Contact/MXKContact.m

during local contacts handling
https://github.com/matrix-org/riot-ios-rageshakes/issues/777
https://github.com/matrix-org/riot-ios-rageshakes/issues/779

Should fix the application crash on "Failed to grow buffer"

---

MatrixKit/Controllers/MXKGroupListViewController.m
MatrixKit/Controllers/MXKGroupListViewController.xib
MatrixKit/Models/Group/MXKSessionGroupsDataSource.h
MatrixKit/Models/Group/MXKSessionGroupsDataSource.m
MatrixKit/Views/MXKCellRendering.h

- MXKGroupListViewController: Support dynamic fonts by enabling self-sizing table view cell.
vector-im/riot-meta#114

Groups: self-management of membership of groups

---

MatrixKit/Models/Contact/MXKContactManager.m

https://github.com/vector-im/riot-ios/issues/1711
Simply delay its execution to the next main loop round

BF: Silent crash at startup in [MXKContactManager loadCachedMatrixContacts]

---

MatrixKit/Models/Room/MXKRoomDataSource.m

according to the `filterMessagesWithURL` property
Fix compilation warnings

Define correctly the live events listener

---

MatrixKit/Utils/MXKEventFormatter.m

https://github.com/vector-im/riot-ios/pull/1844

Redact correctly the stickers

---

MatrixKit/Models/Room/MXKRoomDataSource.h
MatrixKit/Models/Room/MXKRoomDataSource.m

https://github.com/vector-im/riot-ios/issues/1860

Send Stickers: Manage local echo for sticker

---

MatrixKit/Controllers/MXKViewController.m
MatrixKit/Models/Contact/MXKContactManager.m

https://github.com/vector-im/riot-ios/issues/1820
Add debugging logs for lag in typing issue https://github.com/vector-im/riot-ios/issues/1820:
- On local contacts refresh
- On keyboard show/hide

Add debugging logs for issue #1820

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Utils/MXKEventFormatter.m

Closes https://github.com/vector-im/riot-ios/issues/1858

Display quick replies in timeline

---

MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/MatrixKit.h
MatrixKit/Utils/ErrorPresentation/MXKErrorAlertPresentation.h
MatrixKit/Utils/ErrorPresentation/MXKErrorAlertPresentation.m
MatrixKit/Utils/ErrorPresentation/MXKErrorPresentable.h
MatrixKit/Utils/ErrorPresentation/MXKErrorPresentableBuilder.h
MatrixKit/Utils/ErrorPresentation/MXKErrorPresentableBuilder.m
MatrixKit/Utils/ErrorPresentation/MXKErrorPresentation.h
MatrixKit/Utils/ErrorPresentation/MXKErrorViewModel.h
MatrixKit/Utils/ErrorPresentation/MXKErrorViewModel.m

Add convenient error screen display. 
In particular, add a protocol describing error informations to present on screen and a protocol describing how to display error from a view controller.

Error presentation

---

CHANGES.rst
MatrixKit/Controllers/MXKWebViewViewController.m

in order to display some scalar logs.

MXKWebViewVC: enableDebug: support multiple parameters in console.* logs methods

---

MatrixKit/Models/Contact/MXKContactField.m
MatrixKit/Models/Contact/MXKContactManager.m

Reduce time spent on main thread by MXKContactManager.
Contribute to https://github.com/vector-im/riot-ios/issues/1820

MXKContactManager : Reduce time spent on main thread

---

MatrixKit/Controllers/MXKCallViewController.m
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKRoomDataSource.m
MatrixKit/Models/RoomMemberList/MXKRoomMemberCellData.m
MatrixKit/Models/RoomMemberList/MXKRoomMemberListDataSource.m
MatrixKit/Utils/MXKEventFormatter.m
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m

Follows changes made in https://github.com/matrix-org/matrix-ios-sdk/pull/530.
vector-im/riot-ios#1931

MXRoomState: Apply new MXRoomMembers property

---

MatrixKit/Controllers/MXKCallViewController.m
MatrixKit/Controllers/MXKRoomMemberDetailsViewController.m
MatrixKit/Controllers/MXKRoomSettingsViewController.m
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Contact/MXKContactManager.m
MatrixKit/Models/Room/MXKRoomDataSource.m
MatrixKit/Models/RoomList/MXKRecentsDataSource.m
MatrixKit/Models/RoomMemberList/MXKRoomMemberListDataSource.m
MatrixKit/Views/MXKRoomCreationView.m
MatrixKit/Views/PushRule/MXKPushRuleCreationTableViewCell.m
MatrixKit/Views/RoomTitle/MXKRoomTitleView.m
MatrixKit/Views/RoomTitle/MXKRoomTitleViewWithTopic.m

Its access is going to be async.
vector-im/riot-ios#1931

Reduce dependency to room.state

---

CHANGES.rst
MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m

Support room versioning

---

CHANGES.rst
MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Models/Room/MXKRoomDataSourceManager.h
MatrixKit/Models/Room/MXKRoomDataSourceManager.m
Samples/MatrixKitSample/MXKSampleJSQMessagesViewController.m
Samples/MatrixKitSample/MXKSampleMainTableViewController.m

still part of https://github.com/vector-im/riot-ios/issues/1931

Lazy-loading: Make MatrixKit sample build again

---

CHANGES.rst
MatrixKit/Controllers/MXKRoomViewController.m

We enlarge the label, and support multilines

Bug Fix: Improve the display of the reason when the user is kicked

---

MatrixKit/Assets/MatrixKitAssets.bundle/bg.lproj/MatrixKit.strings
MatrixKit/Assets/MatrixKitAssets.bundle/ca.lproj/MatrixKit.strings
MatrixKit/Assets/MatrixKitAssets.bundle/de.lproj/MatrixKit.strings
MatrixKit/Assets/MatrixKitAssets.bundle/es.lproj/MatrixKit.strings
MatrixKit/Assets/MatrixKitAssets.bundle/eu.lproj/MatrixKit.strings
MatrixKit/Assets/MatrixKitAssets.bundle/fr.lproj/MatrixKit.strings
MatrixKit/Assets/MatrixKitAssets.bundle/nl.lproj/MatrixKit.strings
MatrixKit/Assets/MatrixKitAssets.bundle/ru.lproj/MatrixKit.strings
MatrixKit/Assets/MatrixKitAssets.bundle/sq.lproj/MatrixKit.strings
MatrixKit/Assets/MatrixKitAssets.bundle/vi.lproj/MatrixKit.strings
MatrixKit/Assets/MatrixKitAssets.bundle/zh_Hans.lproj/MatrixKit.strings
MatrixKit/Assets/MatrixKitAssets.bundle/zh_Hant.lproj/MatrixKit.strings

As promised at https://github.com/vector-im/riot-ios/pull/2043

Matrix room summaries: Move i18n strings from Riot to MatrixKit

---

MatrixKit/Models/Account/MXKAccountManager.m
MatrixKit/Models/MXKAppSettings.m

Everything seems to work after this but this PR will probably require a bit of testing
https://github.com/vector-im/riot-ios/issues/1924

Remove all calls of [NSUserDefaults synchronize] (#1924)

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Views/EncryptionKeys/MXKEncryptionKeysExportView.m

Fixes https://github.com/vector-im/riot-ios/issues/2072

E2E export: Enter passphrase -> Create passphrase (#2072)

---

CHANGES.rst
MatrixKit/Controllers/MXKAccountDetailsViewController.m
MatrixKit/Models/Contact/MXKContactField.m
MatrixKit/Models/Room/MXKAttachment.m
MatrixKit/Views/MXKImageView.m
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m

Handle correctly media loader cancellation.

---

CHANGES.rst
MatrixKit/Views/Authentication/MXKAuthenticationRecaptchaWebView.h
MatrixKit/Views/Authentication/MXKAuthenticationRecaptchaWebView.m

vector-im/riot-ios/issues/2119

MXKAuthenticationRecaptchaWebView: Use WKWebView so that it can work on iOS 10

---

CHANGES.rst
MatrixKit/Models/Account/MXKAccount.m

 MXKAccount: clear the scan manager database when the session is closed by clearing the cache

---

CHANGES.rst
MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Categories/UIViewController+MatrixKit.h
MatrixKit/Categories/UIViewController+MatrixKit.m
MatrixKit/Controllers/MXKTableViewController.m
MatrixKit/Controllers/MXKViewController.m
MatrixKit/MatrixKit.h

Check also the first commit which changes things a bit.

Create UIViewController+MatrixKit category and factorise code

---

CHANGES.rst
MatrixKit/Utils/MXKTools.m

fixes vector-im/riot-ios/issues/2147
Note: This is a sanity check that does not solve the root issue.

BF: Crash in [MXKTools removeMarkedBlockquotesArtifacts:]

---

CHANGES.rst
MatrixKit/Utils/MXKTools.h
MatrixKit/Utils/MXKTools.m

Add a memory efficient method to reduce image dimensions.

[MXKTools] Improve image resizing

---

MatrixKit/Controllers/MXKRoomMemberDetailsViewController.m
MatrixKit/Controllers/MXKRoomMemberListViewController.m
MatrixKit/Views/DeviceView/MXKDeviceView.m

like in https://github.com/vector-im/riot-ios/pull/2199/commits/ac1cab56e4d5b649bc7bd5d96e6cf012920f9570

Do  `[self->currentAlert textFields].firstObject.text`

---

CHANGES.rst
MatrixKit/Controllers/MXKAuthenticationViewController.m
MatrixKit/Models/Account/MXKAccount.m
MatrixKit/Models/Contact/MXKContactManager.m
MatrixKit/Views/Authentication/MXKAuthenticationFallbackWebView.h
MatrixKit/Views/Authentication/MXKAuthenticationFallbackWebView.m

Follow change made in https://github.com/matrix-org/matrix-ios-sdk/pull/640.

Use new MXLoginResponse class

---

MatrixKit/Controllers/MXKAuthenticationViewController.m

MXKAuthFallbackWebView: Use new MXLoginResponse class

---

MatrixKit/Controllers/MXKAuthenticationViewController.h
MatrixKit/Controllers/MXKAuthenticationViewController.m

For https://github.com/vector-im/riot-ios/issues/2306

MXKAuthVC: Expose showAuthenticationFallBackView

---

MatrixKit/Views/Authentication/MXKAuthInputsView.h

Part of https://github.com/vector-im/riot-ios/issues/2117

Authentication: .well-known support

---

CHANGES.rst
MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m

(vector-im/riot-ios/issues/2318)

Bug Fix: A left room is stuck in my joined room

---

CHANGES.rst
MatrixKit/Controllers/MXKAccountDetailsViewController.m
MatrixKit/Controllers/MXKAttachmentsViewController.m
MatrixKit/Controllers/MXKRoomMemberDetailsViewController.m
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Account/MXKAccount.m
MatrixKit/Models/MXK3PID.m
MatrixKit/Models/Room/MXKAttachment.h
MatrixKitTests/EncryptedAttachmentsTest.m

Fix some potential crashes with ivar using a weak self.

---

CHANGES.rst
MatrixKit/Views/MXKReceiptSendersContainer.h
MatrixKit/Views/MXKReceiptSendersContainer.m

[MXKReceiptSendersContainer] Add possibility to customize `more label` text color

---

CHANGES.rst
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/MXKDataSource.h
MatrixKit/Views/MXKRoomActivitiesView.h
MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.h
MatrixKit/Views/RoomTitle/MXKRoomTitleView.h

TODO remove the `destroy` method by moving its contain in `dealloc`.

MXKRoomViewController: remove the implicit retains of "self".

---

MatrixKit/Assets/MatrixKitAssets.bundle/ja.lproj/MatrixKit.strings

Self-explanatory? :)
Signed-off-by: Jeremy O'Brien <neutral@fastmail.com>

Fix remaining full-width '%' symbols in strings

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Controllers/MXKAuthenticationViewController.h
MatrixKit/Controllers/MXKAuthenticationViewController.xib
MatrixKit/Models/Account/MXKAccount.h
MatrixKit/Models/Account/MXKAccount.m
MatrixKit/Models/Account/MXKAccountManager.h
MatrixKit/Models/Account/MXKAccountManager.m
MatrixKit/Models/Room/MXKRoomDataSource.h
MatrixKit/Views/Authentication/MXKAuthenticationFallbackWebView.h
MatrixKit/Views/Authentication/MXKAuthenticationRecaptchaWebView.h

Signed-off-by: Aaron Raimist <aaron@raim.ist>
Part of https://github.com/vector-im/riot-ios/issues/2345
This probably doesn't need to be included in CHANGES.rst

home server -> homeserver (#2345)

---

MatrixKit/Models/Account/MXKAccount.m
MatrixKit/Models/Room/MXKRoomDataSource.m

Aggregations: manage unreaction

---

MatrixKit/Models/Room/MXKRoomDataSource.h
MatrixKit/Models/Room/MXKRoomDataSource.m

Part of https://github.com/vector-im/riot-ios/issues/2441

Aggregations: Add a settings for computing reactions on messages

---

CHANGES.rst
MatrixKit/Models/Account/MXKAccount.m
MatrixKit/Models/Room/MXKRoomBubbleCellData.h
MatrixKit/Models/Room/MXKRoomDataSource.h
MatrixKit/Models/Room/MXKRoomDataSource.m

A PR to track aggregations changes on the codebase

Aggregations

---

CHANGES.rst
MatrixKit/Models/Contact/MXKContactManager.h
MatrixKit/Models/Contact/MXKContactManager.m

MXContactManager: Add a property to override the users discovering mechanism

---

CHANGES.rst
MatrixKit/Models/Room/MXKRoomDataSource.m
MatrixKit/Utils/EventFormatter/MXKEventFormatter.m

vector-im/riot-ios/issues/2450

MXKRoomDataSource: Support message editing

---

MatrixKit/Models/Room/MXKRoomDataSource.h
MatrixKit/Models/Room/MXKRoomDataSource.m

vector-im/riot-ios/issues/2404

Message Editing: Editing in the timeline

---

MatrixKit/Models/Room/MXKRoomDataSource.h
MatrixKit/Models/Room/MXKRoomDataSource.m

Part of vector-im/riot-ios#2453.
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/673.

Local echo for reactions

---

MatrixKit/Models/Room/MXKRoomDataSource.m

vector-im/riot-ios#2449
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/679

Edits: Support edits in e2e rooms

---

MatrixKit/Views/RoomInputToolbar/MXKRoomInputToolbarView.m

https://github.com/vector-im/riot-ios/issues/2495

Fix potential crash while investigating

---

MatrixKit/Models/Room/MXKRoomDataSource.m

Requires matrix-org/matrix-ios-sdk/pull/686
Handle vector-im/riot-ios/issues/2512

Message Editing: Support emote edition

---

MatrixKit/Models/Room/MXKRoomDataSource.h
MatrixKit/Models/Room/MXKRoomDataSource.m

vector-im/riot-ios/issues/2492

Message Editing: Handle reply edition

---

CHANGES.rst
MatrixKit/Controllers/MXKRoomViewController.h
MatrixKit/Controllers/MXKRoomViewController.m

Part of vector-im/riot-ios/issues/2547 and vector-im/riot-ios#2550
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/690.

Join Room: Support via parameters to better handle federation

---

MatrixKit/Models/Contact/MXKContactManager.m

We let the retry mechanism of the http client handle the potential network errors

MXKContactsManager - Discover Matrix users: Do not loop anymore if the lookup fails.

---

MatrixKit/Controllers/MXKAuthenticationViewController.m

Part of https://github.com/vector-im/riot-ios/issues/2597

Soft logout: SSO support

---

CHANGES.rst
MatrixKit/Models/Account/MXKAccount.m

Signed-off-by: N-Pex <npexdev@gmail.com>

Fix apns push

---

MatrixKit/Controllers/MXKAuthenticationViewController.m
MatrixKit/Models/Account/MXKAccount.m

vector-im/riot-ios/issues/2643

Riot: Ability to disable all identity server functionality via the config file

---

CHANGES.rst
MatrixKit/Controllers/MXKAccountDetailsViewController.m

Part of vector-im/riot-ios/issues/2650

Privacy: Remove the bind true flag from 3PID adds in settings

---

CHANGES.rst
MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Controllers/MXKAuthenticationViewController.h
MatrixKit/Controllers/MXKAuthenticationViewController.m

vector-im/riot-ios/issues/2661

Privacy: Remove the ability to set an IS at login/registration

---

MatrixKit/Controllers/MXKAuthenticationViewController.m

vector-im/riot-ios/issues/2658

Privacy: IS should be customisable for password reset

---

MatrixKit/Controllers/MXKAuthenticationViewController.m
MatrixKit/Models/Account/MXKAccount.m
MatrixKit/Models/Contact/MXKContactManager.m
MatrixKit/Models/MXK3PID.m

Implied by https://github.com/matrix-org/matrix-ios-sdk/pull/716

MXIdentityService: Remove its dependency to MXCredentials

---

MatrixKit/Models/Account/MXKAccount.m
MatrixKit/Models/MXK3PID.m

https://github.com/vector-im/riot-ios/issues/2665
MSC: https://github.com/matrix-org/matrix-doc/pull/2230
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/717

Privacy: Store Identity Server in Account Data (MSC2230)

---

MatrixKit/Models/Contact/MXKContactManager.h
MatrixKit/Models/Contact/MXKContactManager.m

Fixes https://github.com/vector-im/riot-ios/issues/2764
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/732.

BF: Reload contacts lists after an identity server update

---

CHANGES.rst
MatrixKit/Views/MXKImageView.m

BF: MXKImageView: UI API called from background thread

---

CHANGES.rst
MatrixKit/Models/Account/MXKAccount.m

Requires matrix-org/matrix-ios-sdk/pull/746

Improve UIApplication background task management

---

MatrixKit/Controllers/MXKRoomViewController.m

This will fix https://github.com/dinsic-pim/tchap-ios/issues/274

MXKRoomViewController: reset the roomDataSource delegate only when it is equal to the view controller itself

---

MatrixKit/Controllers/MXKRoomMemberDetailsViewController.m
MatrixKit/Views/MXKRoomCreationView.m

Required by https://github.com/matrix-org/matrix-ios-sdk/pull/768.

Room creation: Follow SDK changes

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings

vector-im/riot-ios/issues/2976

Localization: Make sure "Session" replaces "Device" everywhere

---

CHANGES.rst
MatrixKit/Models/Account/MXKAccount.m

It may fix vector-im/riot-ios#3017.

Push notifications: Avoid any automatic deactivation

---

MatrixKit/Controllers/MXKRoomViewController.m

Fixes https://github.com/vector-im/riot-ios/issues/3064

Fix image preview, fixes #3064

---

CHANGES.rst
Libs/README.md
Libs/SwiftUTI/LICENSE
Libs/SwiftUTI/README.md
Libs/SwiftUTI/UTI.swift
MatrixKit.podspec
MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Utils/MXKUTI.swift
Podfile
Podfile.lock

SwiftUTI: Remove the no more maintained pod. Embed code instead

---

CHANGES.rst
MatrixKit/Controllers/MXKAttachmentsViewController.xib

MXKAttachmentsViewController navigation bar respect to Safe Area

---

CHANGES.rst
MatrixKit/Models/Room/MXKRoomDataSource.m

Fix https://github.com/vector-im/riot-ios/issues/3159

Wait for store data ready when finalizing initialization on MXKRoomDataSource

---

CHANGES.rst
MatrixKit/Controllers/MXKCountryPickerViewController.h
MatrixKit/Controllers/MXKCountryPickerViewController.m
MatrixKit/Controllers/MXKCountryPickerViewController.xib
MatrixKit/Controllers/MXKLanguagePickerViewController.h
MatrixKit/Controllers/MXKLanguagePickerViewController.m
MatrixKit/Controllers/MXKLanguagePickerViewController.xib

Replace deprecated UISearchDisplayController by UISearchViewController in MXKCountryPickerViewController and MXKLanguagePickerViewController

Replace deprecated UISearchDisplayController by UISearchViewController

---

CHANGES.rst
MatrixKit/Models/Room/MXKRoomDataSource.m

Ensure Event Existence when Loading MXKRoomDataSource

---

CHANGES.rst
MatrixKit/Models/Room/MXKRoomDataSource.m

Fix https://github.com/vector-im/riot-ios/issues/3337

Fix Opening from Notification Bug

---

CHANGES.rst
MatrixKit/Models/Account/MXKAccountManager.m

Part of vector-im/riot-ios#3369

Make sure PushKit Pusher removed before losing the Push Token

---

CHANGES.rst

Reset the changelog for the next version

Reset Changelog for new version

---

CHANGES.rst
MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Models/MXKAppSettings.m
MatrixKit/Utils/EventFormatter/MXKEventFormatter.m

Part of vector-im/element-ios#3629

Configuration to Collapse State Events on Room Creation

---

CHANGES.rst
MatrixKit/Controllers/MXKAuthenticationViewController.m

vector-im/element-ios/issues/3711

Authentication: Be more open for login flows

---

CHANGES.rst
MatrixKit/Controllers/MXKRoomViewController.m

Fix vector-im/element-ios#3672

Room: Refresh UI When App is Fully Active

---

CHANGES.rst
MatrixKit/Controllers/MXKWebViewViewController.h

fix vector-im/element-ios#3829

Expose Webview object to SDK consumer

---

CHANGES.rst
MatrixKit/Models/Contact/MXKContactManager.h
MatrixKit/Models/Contact/MXKContactManager.m

fix https://github.com/vector-im/element-ios/issues/3833

Add keys properties in MXContactManager and AES encryption algorithm

---

CHANGES.rst
MatrixKit/Models/Account/MXKAccountManager.h
MatrixKit/Models/Account/MXKAccountManager.m
MatrixKit/Models/Contact/MXKContactManager.h
MatrixKit/Models/Contact/MXKContactManager.m

fix https://github.com/vector-im/element-ios/issues/3866

Contacts and Accounts encryption using keys provided by MXKeyProvider

---

CHANGES.rst
MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Controllers/MXKCallViewController.h
MatrixKit/Controllers/MXKCallViewController.m

Part of vector-im/element-ios#3929

Call Screen: Dial Pad Support

---

CHANGES.rst
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/MXKAppSettings.h
MatrixKit/Models/MXKAppSettings.m

fix https://github.com/vector-im/element-ios/issues/3934

Pre-share session keys when opening a room in MXKRoomViewController.

---

CHANGES.rst
MatrixKit.podspec
MatrixKit.xcodeproj/xcshareddata/xcschemes/MatrixKitSample.xcscheme
Podfile
Podfile.lock

vector-im/element-ios/issues/4120

Pods: Update JSQMessagesViewController, DTCoreText, Down

---

CHANGES.rst
MatrixKit/Controllers/MXKRoomViewController.m

fix https://github.com/vector-im/element-ios/issues/4209

Fixed: RR are not sent if a typing notification is shown in the timeline

---

CHANGES.rst
MatrixKit/Models/Account/MXKAccount.m
fastlane/Fastfile

Fix vector-im/element-ios#4054

Do not Show Certain Errors on Initial Sync

---

MatrixKit/Models/Account/MXKAccount.m

To improve logs for vector-im/element-ios#3921

Improvements for Unexpected Cache Clears

---

CHANGES.rst
MatrixKit/Models/Account/MXKAccount.m
MatrixKit/Models/RoomList/MXKInterleavedRecentsDataSource.m
MatrixKit/Models/RoomList/MXKRecentCellData.m
MatrixKit/Models/RoomList/MXKRecentCellDataStoring.h
MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m
MatrixKit/Utils/EventFormatter/MXKEventFormatter.m

Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1108

MXRoomSummary: Refactor Last Message Properties

---

CHANGES.rst
MatrixKit/Models/Room/MXKRoomDataSource.h
MatrixKit/Models/Room/MXKRoomDataSource.m

Exposed methods on the MXRoomDataSource for seding audio files and voice messages.

Send audio files and voice messages

---

CHANGES.rst
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKRoomDataSource.m

Fixes redaction on main room issue and scrolling to top issue.

Fix Redactions on Virtual Timeline

---

CHANGES.rst
MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
MatrixKit/Utils/MXKTools.m

fixes vector-im/element-ios#2592, vector-im/element-ios#3758, vector-im/element-ios#4448 and a bunch of others.

style blockquotes as blocks

---

CHANGES.rst
MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Models/Room/MXKAttachment.h
MatrixKit/Models/Room/MXKAttachment.m
MatrixKit/Models/Room/MXKRoomBubbleCellData.m
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m

Added specific voice message attachment type and microphone permission localizable string.

Voice messages

---

CHANGES.rst
MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Controllers/MXKCallViewController.h
MatrixKit/Controllers/MXKCallViewController.m
MatrixKit/Controllers/MXKCallViewController.xib

Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1138

CallVC: Audio Routing Menu

---

CHANGES.rst
MatrixKit/Models/Room/MXKAttachment.m

Related to https://github.com/vector-im/element-ios/issues/4094

Add support for all voice message types

---

CHANGES.rst
MatrixKit/Models/Room/MXKRoomDataSource.h
MatrixKit/Models/Room/MXKRoomDataSource.m

Implemented retrying for failed audio file and voice messages always calling completion blocks.

Failed voice and audio message sending retries

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGES.md
CONTRIBUTING.md
CONTRIBUTING.rst
MatrixKit.xcodeproj/project.pbxproj
changelog.d/.gitignore
changelog.d/4393.build
changelog.d/4393.doc
changelog.d/_template.md.jinja
towncrier.toml

Kit part of part for vector-im/element-ios#4393.

Enable Towncrier

---

MatrixKit/Controllers/MXKRecentListViewController.h
MatrixKit/Controllers/MXKRecentListViewController.m
MatrixKit/Models/RoomList/MXKRecentCellData.m
MatrixKit/Models/RoomList/MXKRecentCellDataStoring.h
MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m

Fixes https://github.com/vector-im/element-ios/issues/4501

[Spaces] M10.5 Show suggested in room lists #4501

---

MatrixKit/Models/Room/MXKRoomDataSource.m
changelog.d/4383.change

Fix vector-im/element-ios#4383
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1213

Lazy load Room Receipts

---

MatrixKit.podspec
MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Categories/UIScrollView+MatrixKit.h
MatrixKit/Categories/UIScrollView+MatrixKit.m
MatrixKit/Controllers/MXKContactListViewController.m
MatrixKit/Controllers/MXKCountryPickerViewController.m
MatrixKit/Controllers/MXKGroupListViewController.m
MatrixKit/Controllers/MXKLanguagePickerViewController.m
MatrixKit/Controllers/MXKRecentListViewController.m
MatrixKit/Controllers/MXKRoomMemberListViewController.m
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Controllers/MXKSearchViewController.m
MatrixKit/Controllers/MXKTableViewController.m
MatrixKit/MatrixKit.h
MatrixKit/Views/MXKImageView.m
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m
Podfile
Podfile.lock
changelog.d/4693.api

We need one extra release where we just mark iOS 11 as deprecated before going ahead with this.

Revert "vector-im/element-ios/issues/4693 - Drop iOS 11 and lower support.

---

.gitignore
changelog.d/pr-892.misc

No issue for this one, should be less annoying with this added though 🙂

Add .DS_Store to .gitignore.

---

MatrixKit/Models/Room/MXKRoomDataSource.m
changelog.d/4788.bugfix

Fix vector-im/element-ios#4788

Fix timeline regression

---

MatrixKit/Models/Contact/MXKContactManager.m
changelog.d/4803.bugfix

Fix https://github.com/vector-im/element-ios/issues/4803

Authentication screen: Unexpected request to access the contact book

---

MatrixKit/Controllers/MXKRoomMemberDetailsViewController.h
MatrixKit/Controllers/MXKRoomMemberDetailsViewController.m

Needed by https://github.com/vector-im/element-ios/issues/4682

[Spaces] M10.8 Browsing users in a space #4682

---

MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKRoomDataSource.m
changelog.d/1771.change
changelog.d/4822.bugfix

This PR adds logs to `MXKRoomDataSource` to better understand vector-im/element-ios#1771
Fixes vector-im/element-ios#4822
Requires https://github.com/matrix-org/matrix-ios-sdk/pull/1225

Add logs for local echo issues

---

MatrixKit/Controllers/MXKAuthenticationViewController.h
MatrixKit/Controllers/MXKAuthenticationViewController.m
MatrixKit/Models/Account/MXKAccount.h
MatrixKit/Models/Account/MXKAccount.m
MatrixKit/Models/Account/MXKAccountManager.h
MatrixKit/Models/Account/MXKAccountManager.m
changelog.d/4255.feature

Fixes vector-im/element-ios/issues/4255 - Device de/rehydration flows.

Device de/rehydration flows

---

MatrixKit/Assets/MatrixKitAssets.bundle/en.lproj/MatrixKit.strings
MatrixKit/Controllers/MXKRoomViewController.h
MatrixKit/Controllers/MXKRoomViewController.m
changelog.d/4830.api

* exposed various room joining results
* converged room joining failure handlers
* bailing our early when possible

Exposed more room joining result types in the completion handler.

---

MatrixKit/Models/RoomList/MXKSessionRecentsDataSource.m

- `MXKSessionRecentsDataSource`: listen to current space events

[Spaces] pre release fixes

---

MatrixKit.xcodeproj/project.pbxproj
MatrixKit/Controllers/MXKActivityHandlingViewController.h
MatrixKit/Controllers/MXKActivityHandlingViewController.m
MatrixKit/Controllers/MXKViewController.h
MatrixKit/Controllers/MXKViewController.m
MatrixKit/Controllers/MXKViewControllerActivityHandling.h
MatrixKit/Controllers/MXKViewControllerHandling.h

Separated activity indicator part from `MXViewController`

[Spaces] M10.6.1 Handle space link #4498

---

MatrixKit/Controllers/MXKAttachmentsViewController.m
MatrixKit/Controllers/MXKAuthenticationViewController.m
MatrixKit/Controllers/MXKRecentListViewController.m
MatrixKit/Controllers/MXKRoomMemberListViewController.m
MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Controllers/MXKSearchViewController.m
MatrixKit/Controllers/MXKWebViewViewController.m
MatrixKit/Models/RoomList/MXKInterleavedRecentsDataSource.m
MatrixKit/Views/MXKTableViewCell/MXKTableViewCellWithButtons.m
MatrixKit/Views/RoomBubbleList/MXKRoomBubbleTableViewCell.m

Deployment target is iOS 9 now, so these can go.
Signed-off-by: Adlai Holler <adlai@icloud.com>

Remove iOS 7 auto layout code paths

---

MatrixKit/Controllers/MXKRoomViewController.m
changelog.d/5071.bugfix

Part of the fix for https://github.com/vector-im/element-ios/issues/5071.

Keep strong refs to views before display.

---

MatrixKit/Models/Room/MXKRoomBubbleCellDataWithAppendingMode.m
changelog.d/5110.bugfix

Fixes https://github.com/vector-im/element-ios/issues/5110

Crash generating bubble text

---

MatrixKit/Models/MXKAppSettings.m
MatrixKit/Utils/EventFormatter/MXKEventFormatter.m
changelog.d/5105.bugfix

Part of fix for vector-im/element-ios#5105

Fix room ordering

---

MatrixKit/Models/Room/MXKRoomDataSource.m
changelog.d/5111.bugfix

Fixes https://github.com/vector-im/element-ios/issues/5111

Missing messages on rooms with paired virtual room

---

MatrixKit/Controllers/MXKRoomViewController.m
MatrixKit/Models/Room/MXKAttachment.h
MatrixKit/Models/Room/MXKAttachment.m
MatrixKit/Utils/MXKUTI.swift

Another small tweak to the share sheet on iOS 12.

Tweak to Share Sheet

---

MatrixKit/Categories/MXAggregatedReactions+MatrixKit.h
changelog.d/5174.bugfix

https://github.com/vector-im/element-ios/issues/5174

Fix cycle dependencies

---

MatrixKit.podspec
changelog.d/5020.misc

Part of https://github.com/vector-im/element-ios/issues/5020

Podspec: Mark MatrixKit pod as deprecated
